import { StoryChapterDefinition } from './StoryTypes';

// 第八章：王陵三证
// 三关取证·boss 级大章（身份证/祭祀证/占卜证各需一轮占卜+一次挖掘，证齐开核心）
// 字量 44，全部来自 ChapterCharMap 第 8 章分配（编号 159~202）。
export const CHAPTER_EIGHT_ID = 'chapter-8-tomb-three-proofs';
// 守陵·阿陵 站位（坐标待 Cocos 微调）；进章传送落其旁。

export const CHAPTER_EIGHT_FRAGMENT_CARDS = [
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-001', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-001', cardId: 'catalog-u5df7', character: '巷' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-002', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-002', cardId: 'catalog-u8857', character: '街' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-003', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-003', cardId: 'catalog-u8def', character: '路' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-004', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-004', cardId: 'catalog-u8f66', character: '车' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-005', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-005', cardId: 'catalog-u8239', character: '船' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-006', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-006', cardId: 'catalog-u9a6c', character: '马' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-007', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-007', cardId: 'catalog-u6865', character: '桥' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-008', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-008', cardId: 'catalog-u9053', character: '道' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-009', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-009', cardId: 'catalog-u5761', character: '坡' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-010', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-010', cardId: 'catalog-u4e95', character: '井' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-011', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-011', cardId: 'catalog-u7f38', character: '缸' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-012', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-012', cardId: 'catalog-u76c6', character: '盆' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-013', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-013', cardId: 'catalog-u676f', character: '杯' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-014', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-014', cardId: 'catalog-u7897', character: '碗' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-015', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-015', cardId: 'catalog-u52fa', character: '勺' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-016', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-016', cardId: 'catalog-u7b77', character: '筷' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-017', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-017', cardId: 'catalog-u5200', character: '刀' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-018', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-018', cardId: 'catalog-u5c3a', character: '尺' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-019', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-019', cardId: 'catalog-u7b14', character: '笔' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-020', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-020', cardId: 'catalog-u7eb8', character: '纸' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-021', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-021', cardId: 'catalog-u4e66', character: '书' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-022', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-022', cardId: 'catalog-u672c', character: '本' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-023', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-023', cardId: 'catalog-u70ec', character: '烬' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-024', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-024', cardId: 'catalog-u753b', character: '画' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-025', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-025', cardId: 'catalog-u56fe', character: '图' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-026', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-026', cardId: 'catalog-u518c', character: '册' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-027', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-027', cardId: 'catalog-u6821', character: '校' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-028', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-028', cardId: 'catalog-u5b66', character: '学' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-029', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-029', cardId: 'catalog-u5e08', character: '师' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-030', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-030', cardId: 'catalog-u751f', character: '生' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-031', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-031', cardId: 'catalog-u73ed', character: '班' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-032', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-032', cardId: 'catalog-u8bfe', character: '课' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-033', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-033', cardId: 'catalog-u6587', character: '文' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-034', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-034', cardId: 'catalog-u6570', character: '数' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-035', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-035', cardId: 'catalog-u8bed', character: '语' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-036', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-036', cardId: 'catalog-u82f1', character: '英' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-037', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-037', cardId: 'catalog-u8d70', character: '走' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-038', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-038', cardId: 'catalog-u8dd1', character: '跑' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-039', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-039', cardId: 'catalog-u8df3', character: '跳' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-040', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-040', cardId: 'catalog-u7ad9', character: '站' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-041', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-041', cardId: 'catalog-u5750', character: '坐' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-042', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-042', cardId: 'catalog-u5367', character: '卧' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-043', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-043', cardId: 'catalog-u884c', character: '行' },
  { seekStepId: 'chapter-8-tomb-three-proofs-seek-044', lessonStepId: 'chapter-8-tomb-three-proofs-lesson-044', cardId: 'catalog-u98de', character: '飞' },
] as const;

export const chapterEightDefinition: StoryChapterDefinition = {
  id: CHAPTER_EIGHT_ID,
  title: '第八章：王陵三证',
  firstStepId: 'chapter-8-tomb-three-proofs-opening',
  steps: [
    {
      id: 'chapter-8-tomb-three-proofs-opening',
      chapterId: CHAPTER_EIGHT_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '典册终于归架，可最后一道裂纹越出城郭，直指城外幽深的王陵。神道石兽夹立，陵门却紧紧闭着；守陵·阿陵拦住你：身份、祭祀、占卜三证未齐，陵门不开。' },
        { speaker: '贞人师', text: '这一程在陵道上、祭坑边、封土之间。守陵·阿陵守着一桩要紧的事，需你以甲骨一一卜算。' },
        { speaker: '守陵·阿陵', text: '守卜人，我名阿陵。此去事繁，你若相助，便以你卜出的甲骨引我趋吉辨伪——如何？' },
        { speaker: '提示', kind: 'system', text: '第八章：王陵三证开启。当前目标：寻到守陵·阿陵，在这一程各处寻回失语的王陵三证甲骨碎片。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-reach-npc',
      checkpoint: true,
    },
    {
      id: 'chapter-8-tomb-three-proofs-reach-npc',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 启程', detail: '走到守陵·阿陵身边，听他（她）讲清这一程要卜的事。', storyLocationId: 'chapter-8-royal-tomb-npc', targetRadius: 200 },
      completeOn: 'npc-reached',
      nextStepId: 'chapter-8-tomb-three-proofs-npc-dialogue',
    },
    {
      id: 'chapter-8-tomb-three-proofs-npc-dialogue',
      chapterId: CHAPTER_EIGHT_ID,
      dialogue: [
        { speaker: '守陵·阿陵', text: '我这一程要办的，是「王陵三证」。这一带散着44枚记着这事的老刻，自打天意断了就再没响过。' },
        { speaker: '你', text: '我不是来指路，是来听骨。你若信我，便一枚枚唤醒它们，兆纹自会引我们看清明细。' },
        { speaker: '守陵·阿陵', text: '那便随我来。沿途的碎甲你且一枚枚挖出、认明——「巷街路车船马桥道坡井缸盆杯碗勺筷刀尺笔纸书本烬画图册校学师生班课文数语英走跑跳站坐卧行飞」这些，都在这一程里。' },
        { speaker: '提示', kind: 'system', text: '任务更新：在第八章：王陵三证中挖掘并发掘失语的甲骨碎片。每寻回一枚，阿陵便信你一分。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-001',
      checkpoint: true,
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-001',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '陵道入口的土层里沉着微光。挖出「巷」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-001',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-001',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识巷字', detail: '观察骨纹，认出这是「巷」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-002',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-002',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '神道石兽的土层里沉着微光。挖出「街」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-002',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-002',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识街字', detail: '观察骨纹，认出这是「街」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-003',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-003',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '墓道转角的土层里沉着微光。挖出「路」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-003',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-003',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识路字', detail: '观察骨纹，认出这是「路」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-004',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-004',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '封土之侧的土层里沉着微光。挖出「车」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-004',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-004',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识车字', detail: '观察骨纹，认出这是「车」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-005',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-005',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '祭坑边缘的土层里沉着微光。挖出「船」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-005',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-005',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识船字', detail: '观察骨纹，认出这是「船」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-006',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-006',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '车马坑中的土层里沉着微光。挖出「马」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-006',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-006',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识马字', detail: '观察骨纹，认出这是「马」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-007',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-007',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '船坞遗迹的土层里沉着微光。挖出「桥」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-007',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-007',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识桥字', detail: '观察骨纹，认出这是「桥」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-008',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-008',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '青铜马厩的土层里沉着微光。挖出「道」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-008',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-008',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识道字', detail: '观察骨纹，认出这是「道」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-009',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-009',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '石桥残段的土层里沉着微光。挖出「坡」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-009',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-009',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识坡字', detail: '观察骨纹，认出这是「坡」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-010',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-010',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '坡道尽头的土层里沉着微光。挖出「井」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-010',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-010',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识井字', detail: '观察骨纹，认出这是「井」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-011',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-011',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '水井淤塞的土层里沉着微光。挖出「缸」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-011',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-011',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识缸字', detail: '观察骨纹，认出这是「缸」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-012',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-012',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '陶缸碎处的土层里沉着微光。挖出「盆」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-012',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-012',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识盆字', detail: '观察骨纹，认出这是「盆」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-013',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-013',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '漆杯倾倒的土层里沉着微光。挖出「杯」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-013',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-013',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识杯字', detail: '观察骨纹，认出这是「杯」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-014',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-014',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '陶碗残片的土层里沉着微光。挖出「碗」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-014',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-014',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识碗字', detail: '观察骨纹，认出这是「碗」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-015',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-015',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '铜勺锈埋的土层里沉着微光。挖出「勺」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-015',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-015',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识勺字', detail: '观察骨纹，认出这是「勺」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-016',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-016',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '竹筷散乱的土层里沉着微光。挖出「筷」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-016',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-016',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识筷字', detail: '观察骨纹，认出这是「筷」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-017',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-017',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '青铜刀匣的土层里沉着微光。挖出「刀」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-017',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-017',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识刀字', detail: '观察骨纹，认出这是「刀」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-018',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-018',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '量土之尺的土层里沉着微光。挖出「尺」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-018',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-018',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识尺字', detail: '观察骨纹，认出这是「尺」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-019',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-019',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '卜笔干涸的土层里沉着微光。挖出「笔」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-019',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-019',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识笔字', detail: '观察骨纹，认出这是「笔」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-020',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-020',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '残纸裹简的土层里沉着微光。挖出「纸」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-020',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-020',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识纸字', detail: '观察骨纹，认出这是「纸」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-021',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-021',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '书简半腐的土层里沉着微光。挖出「书」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-021',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-021',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识书字', detail: '观察骨纹，认出这是「书」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-022',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-022',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '木牍泡水的土层里沉着微光。挖出「本」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-022',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-022',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识本字', detail: '观察骨纹，认出这是「本」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-midstream',
    },
    {
      id: 'chapter-8-tomb-three-proofs-midstream',
      chapterId: CHAPTER_EIGHT_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '半数碎甲归位的刹那，阿陵一直绷着的神色松了下来。这一程的脉络，第一次在你们之间连成线。' },
        { speaker: '守陵·阿陵', text: '原以为这桩「王陵三证」只是我一家的事。可你挖出的骨片，真的一枚枚在我眼前活了——这回我信你。' },
        { speaker: '神秘低语', text: '……骨归其序，事乃成章……' },
        { speaker: '贞人师', text: '中段已过，阿陵终肯托付。继续寻回余下的碎甲，这一程的真相便近了。' },
        { speaker: '提示', kind: 'system', text: '中段：22字已聚，阿陵托付于你。继续入深处，寻回余下碎甲。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-023',
      checkpoint: true,
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-023',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '灰烬余烬的土层里沉着微光。挖出「烬」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-023',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-023',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识烬字', detail: '观察骨纹，认出这是「烬」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-024',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-024',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '壁画剥落的土层里沉着微光。挖出「画」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-024',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-024',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识画字', detail: '观察骨纹，认出这是「画」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-025',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-025',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '舆图残卷的土层里沉着微光。挖出「图」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-025',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-025',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识图字', detail: '观察骨纹，认出这是「图」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-026',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-026',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '典册散架的土层里沉着微光。挖出「册」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-026',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-026',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识册字', detail: '观察骨纹，认出这是「册」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-027',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-027',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '校勘之台的土层里沉着微光。挖出「校」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-027',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-027',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识校字', detail: '观察骨纹，认出这是「校」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-028',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-028',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '学室倾颓的土层里沉着微光。挖出「学」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-028',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-028',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识学字', detail: '观察骨纹，认出这是「学」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-029',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-029',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '师位空悬的土层里沉着微光。挖出「师」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-029',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-029',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识师字', detail: '观察骨纹，认出这是「师」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-030',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-030',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '生徒列席的土层里沉着微光。挖出「生」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-030',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-030',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识生字', detail: '观察骨纹，认出这是「生」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-031',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-031',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '班列错乱的土层里沉着微光。挖出「班」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-031',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-031',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识班字', detail: '观察骨纹，认出这是「班」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-032',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-032',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '课业简断的土层里沉着微光。挖出「课」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-032',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-032',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识课字', detail: '观察骨纹，认出这是「课」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-033',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-033',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '铭文漫漶的土层里沉着微光。挖出「文」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-033',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-033',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识文字', detail: '观察骨纹，认出这是「文」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-034',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-034',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '数字模糊的土层里沉着微光。挖出「数」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-034',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-034',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识数字', detail: '观察骨纹，认出这是「数」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-035',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-035',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '语焉不详的土层里沉着微光。挖出「语」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-035',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-035',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识语字', detail: '观察骨纹，认出这是「语」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-036',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-036',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '异文残碑的土层里沉着微光。挖出「英」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-036',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-036',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识英字', detail: '观察骨纹，认出这是「英」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-037',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-037',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '远行车辙的土层里沉着微光。挖出「走」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-037',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-037',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识走字', detail: '观察骨纹，认出这是「走」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-038',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-038',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '奔马之塑的土层里沉着微光。挖出「跑」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-038',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-038',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识跑字', detail: '观察骨纹，认出这是「跑」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-039',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-039',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '跃沟之痕的土层里沉着微光。挖出「跳」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-039',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-039',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识跳字', detail: '观察骨纹，认出这是「跳」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-040',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-040',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '驻足之石的土层里沉着微光。挖出「站」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-040',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-040',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识站字', detail: '观察骨纹，认出这是「站」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-041',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-041',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '箕坐之痕的土层里沉着微光。挖出「坐」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-041',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-041',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识坐字', detail: '观察骨纹，认出这是「坐」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-042',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-042',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '偃卧之像的土层里沉着微光。挖出「卧」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-042',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-042',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识卧字', detail: '观察骨纹，认出这是「卧」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-043',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-043',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '行旅浮雕的土层里沉着微光。挖出「行」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-043',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-043',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识行字', detail: '观察骨纹，认出这是「行」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-seek-044',
    },
    {
      id: 'chapter-8-tomb-three-proofs-seek-044',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 寻骨', detail: '飞鸟纹砖的土层里沉着微光。挖出「飞」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-lesson-044',
    },
    {
      id: 'chapter-8-tomb-three-proofs-lesson-044',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 辨识飞字', detail: '观察骨纹，认出这是「飞」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-fragment-awakens',
    },
    {
      id: 'chapter-8-tomb-three-proofs-fragment-awakens',
      chapterId: CHAPTER_EIGHT_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '44枚王陵三证碎甲在掌心排开。你按这一程的脉络理好，骨纹竟投出一道微光，照见阿陵要办之事的去向。' },
        { speaker: '神秘低语', text: '……王陵三证毕，骨已成章……' },
        { speaker: '你', text: '原来这一程记下的不是死物，是「巷街路车船马桥道坡井缸盆杯碗勺筷刀尺笔纸书本烬画图册校学师生班课文数语英走跑跳站坐卧行飞」里活着的学问。它们齐了，去路才显在眼前。' },
        { speaker: '守陵·阿陵', text: '我听不见金光里的声音，可骨片真的在你手里连成了路！守卜人，你果然是贞人师说的那个人。' },
        { speaker: '提示', kind: 'system', text: '获得：「巷街路车船马桥道坡井缸盆杯碗勺筷刀尺笔纸书本烬画图册校学师生班课文数语英走跑跳站坐卧行飞」44枚王陵三证甲骨碎片。卜力已苏醒，可落为天意之辞。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-first-request',
    },
    {
      id: 'chapter-8-tomb-three-proofs-first-request',
      chapterId: CHAPTER_EIGHT_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '44枚碎甲归位，阿陵这一桩「王陵三证」的脉络已清。可尚有未解的悬疑，要借卜力一问。' },
        { speaker: '守陵·阿陵', text: '守卜人，这44枚甲骨记下的事，我已信了八九分。可还有三桩悬案，能用这些字卜一卜么？' },
        { speaker: '你', text: '（你斟酌：三问牵连，当一卜接一卜地解。取过一枚甲骨——先卜其一，其余的，且待兆纹引你去看。）' },
        { speaker: '贞人师', text: '去吧。以这一程的卜力，为阿陵卜算「身份之证、祭祀之证、占卜之证」三桩悬案。每解一桩，卜力便积一分。' },
        { speaker: '提示', kind: 'system', text: '守卜任务开启（第一轮）：为守陵·阿陵卜算「身份之证」，留意兆纹里多出的那道裂纹。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-enter-temple',
      checkpoint: true,
    },
    {
      id: 'chapter-8-tomb-three-proofs-enter-temple',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第八章：王陵三证 · 问卜', detail: '随守陵·阿陵返回宗庙内殿，准备以本章甲骨问卜。', storyLocationId: 'city-divination-temple', targetRadius: 110 },
      completeOn: 'temple-entered',
      nextStepId: 'chapter-8-tomb-three-proofs-take-seat',
    },
    {
      id: 'chapter-8-tomb-three-proofs-take-seat',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '问卜 · 入席', detail: '走到内殿占卜席前，点击“坐下”，听守陵·阿陵讲清要卜之事。' },
      completeOn: 'temple-seat-reached',
      nextStepId: 'chapter-8-tomb-three-proofs-divination-1',
    },
    {
      id: 'chapter-8-tomb-three-proofs-divination-1',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第1轮问卜 · 身份之证', detail: '守陵·阿陵请你以本章甲骨卜算「身份之证」。' },
      completeOn: 'divination-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-divination-2',
      checkpoint: true,
    },
    {
      id: 'chapter-8-tomb-three-proofs-divination-2',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第2轮问卜 · 祭祀之证', detail: '守陵·阿陵请你以本章甲骨卜算「祭祀之证」。' },
      completeOn: 'divination-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-divination-3',
      checkpoint: true,
    },
    {
      id: 'chapter-8-tomb-three-proofs-divination-3',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '第3轮问卜 · 占卜之证', detail: '守陵·阿陵请你以本章甲骨卜算「占卜之证」。' },
      completeOn: 'divination-completed',
      nextStepId: 'chapter-8-tomb-three-proofs-leave-seat',
    },
    {
      id: 'chapter-8-tomb-three-proofs-leave-seat',
      chapterId: CHAPTER_EIGHT_ID,
      objective: { title: '异常兆纹', detail: '完成三轮占卜后起身，查看甲骨额外显出的那道裂纹。' },
      completeOn: 'result-confirmed',
      nextStepId: 'chapter-8-tomb-three-proofs-clue-revealed',
    },
    {
      id: 'chapter-8-tomb-three-proofs-clue-revealed',
      chapterId: CHAPTER_EIGHT_ID,
      dialogue: [
        { speaker: '守陵·阿陵', text: '原来「身份之证、祭祀之证、占卜之证」三问，兆纹都指向下一处——三证齐聚，陵门洞开，最深处一具指天卜骨静候——重续通天之契，在此一举。' },
        { speaker: '旁白', kind: 'narration', text: '三卜既毕，兆纹并未熄灭。几道裂纹缓缓延伸，竟越过这一程，指向「重续通天之契」。' },
        { speaker: '神秘低语', text: '……重续通天之契……有骨……待人相续……' },
        { speaker: '贞人师', text: '三轮卜辞彼此牵引，这道裂纹拐出了这一程——下一处碎甲，在「重续通天之契」里。' },
        { speaker: '提示', kind: 'system', text: '第八章：王陵三证完成。获得线索「重续通天之契」，下一章已开启。' },
      ],
      completeOn: 'dialogue-completed',
      checkpoint: true,
    },
  ],
};
