import { StoryChapterDefinition } from './StoryTypes';

// 第六章：古墟残灯
// 废墟点灯·顺序解谜链（点错重来，强调顺序不可错）
// 字量 32，全部来自 ChapterCharMap 第 6 章分配（编号 089~120）。
export const CHAPTER_SIX_ID = 'chapter-6-ruins-lamp';
// 灯匠·阿烛 站位（坐标待 Cocos 微调）；进章传送落其旁。
// 古墟残灯位于王陵祭祀区的陆地。旧坐标 (-1100, -1500) 正落在洹水湖深水区，
// 会导致人物传送后无法移动，故固定在与本章发掘点相同的古墟陆地区域。
export const CHAPTER_SIX_NPC_POSITION = { x: 1500, y: -3180 } as const;

export const CHAPTER_SIX_FRAGMENT_CARDS = [
  { seekStepId: 'chapter-6-ruins-lamp-seek-001', lessonStepId: 'chapter-6-ruins-lamp-lesson-001', cardId: 'catalog-u65f6', character: '时' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-002', lessonStepId: 'chapter-6-ruins-lamp-lesson-002', cardId: 'catalog-u5206', character: '分' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-003', lessonStepId: 'chapter-6-ruins-lamp-lesson-003', cardId: 'catalog-u523b', character: '刻' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-004', lessonStepId: 'chapter-6-ruins-lamp-lesson-004', cardId: 'catalog-u5e74', character: '年' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-005', lessonStepId: 'chapter-6-ruins-lamp-lesson-005', cardId: 'catalog-u5c81', character: '岁' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-006', lessonStepId: 'chapter-6-ruins-lamp-lesson-006', cardId: 'catalog-u671d', character: '朝' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-007', lessonStepId: 'chapter-6-ruins-lamp-lesson-007', cardId: 'catalog-u5915', character: '夕' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-008', lessonStepId: 'chapter-6-ruins-lamp-lesson-008', cardId: 'catalog-u663c', character: '昼' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-009', lessonStepId: 'chapter-6-ruins-lamp-lesson-009', cardId: 'catalog-u591c', character: '夜' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-010', lessonStepId: 'chapter-6-ruins-lamp-lesson-010', cardId: 'catalog-u5149', character: '光' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-011', lessonStepId: 'chapter-6-ruins-lamp-lesson-011', cardId: 'catalog-u5934', character: '头' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-012', lessonStepId: 'chapter-6-ruins-lamp-lesson-012', cardId: 'catalog-u9762', character: '面' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-013', lessonStepId: 'chapter-6-ruins-lamp-lesson-013', cardId: 'catalog-u773c', character: '眼' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-014', lessonStepId: 'chapter-6-ruins-lamp-lesson-014', cardId: 'catalog-u8033', character: '耳' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-015', lessonStepId: 'chapter-6-ruins-lamp-lesson-015', cardId: 'catalog-u53e3', character: '口' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-016', lessonStepId: 'chapter-6-ruins-lamp-lesson-016', cardId: 'catalog-u9f3b', character: '鼻' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-017', lessonStepId: 'chapter-6-ruins-lamp-lesson-017', cardId: 'catalog-u624b', character: '手' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-018', lessonStepId: 'chapter-6-ruins-lamp-lesson-018', cardId: 'catalog-u8db3', character: '足' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-019', lessonStepId: 'chapter-6-ruins-lamp-lesson-019', cardId: 'catalog-u5fc3', character: '心' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-020', lessonStepId: 'chapter-6-ruins-lamp-lesson-020', cardId: 'catalog-u8eab', character: '身' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-021', lessonStepId: 'chapter-6-ruins-lamp-lesson-021', cardId: 'catalog-u9aa8', character: '骨' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-022', lessonStepId: 'chapter-6-ruins-lamp-lesson-022', cardId: 'catalog-u76ae', character: '皮' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-023', lessonStepId: 'chapter-6-ruins-lamp-lesson-023', cardId: 'catalog-u6bdb', character: '毛' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-024', lessonStepId: 'chapter-6-ruins-lamp-lesson-024', cardId: 'catalog-u53d1', character: '发' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-025', lessonStepId: 'chapter-6-ruins-lamp-lesson-025', cardId: 'catalog-u9f7f', character: '齿' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-026', lessonStepId: 'chapter-6-ruins-lamp-lesson-026', cardId: 'catalog-u820c', character: '舌' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-027', lessonStepId: 'chapter-6-ruins-lamp-lesson-027', cardId: 'catalog-u80a9', character: '肩' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-028', lessonStepId: 'chapter-6-ruins-lamp-lesson-028', cardId: 'catalog-u80f8', character: '胸' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-029', lessonStepId: 'chapter-6-ruins-lamp-lesson-029', cardId: 'catalog-u8170', character: '腰' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-030', lessonStepId: 'chapter-6-ruins-lamp-lesson-030', cardId: 'catalog-u817f', character: '腿' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-031', lessonStepId: 'chapter-6-ruins-lamp-lesson-031', cardId: 'catalog-u811a', character: '脚' },
  { seekStepId: 'chapter-6-ruins-lamp-seek-032', lessonStepId: 'chapter-6-ruins-lamp-lesson-032', cardId: 'catalog-u6307', character: '指' },
] as const;

export const chapterSixDefinition: StoryChapterDefinition = {
  id: CHAPTER_SIX_ID,
  title: '第六章：古墟残灯',
  firstStepId: 'chapter-6-ruins-lamp-opening',
  steps: [
    {
      id: 'chapter-6-ruins-lamp-opening',
      chapterId: CHAPTER_SIX_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '护送归途的最后一道裂纹拐下大道，钻进一片荒废坍圮的旧宗庙。断柱残阶之间，一盏盏残灯尽数熄灭；守着废墟、想让残灯重亮的灯匠·阿烛正等着你。' },
        { speaker: '贞人师', text: '这一程在废墟里、残灯下、断柱之间。灯匠·阿烛守着一桩要紧的事，需你以甲骨一一卜算。' },
        { speaker: '灯匠·阿烛', text: '守卜人，我名阿烛。此去事繁，你若相助，便以你卜出的甲骨引我趋吉辨伪——如何？' },
        { speaker: '提示', kind: 'system', text: '第六章：古墟残灯开启。当前目标：寻到灯匠·阿烛，在这一程各处寻回失语的废墟点灯甲骨碎片。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-6-ruins-lamp-reach-npc',
      checkpoint: true,
    },
    {
      id: 'chapter-6-ruins-lamp-reach-npc',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 启程', detail: '走到灯匠·阿烛身边，听他（她）讲清这一程要卜的事。', targetX: -1100, targetY: -1500, targetRadius: 200 },
      completeOn: 'npc-reached',
      nextStepId: 'chapter-6-ruins-lamp-npc-dialogue',
    },
    {
      id: 'chapter-6-ruins-lamp-npc-dialogue',
      chapterId: CHAPTER_SIX_ID,
      dialogue: [
        { speaker: '灯匠·阿烛', text: '我这一程要办的，是「废墟点灯」。这一带散着32枚记着这事的老刻，自打天意断了就再没响过。' },
        { speaker: '你', text: '我不是来指路，是来听骨。你若信我，便一枚枚唤醒它们，兆纹自会引我们看清明细。' },
        { speaker: '灯匠·阿烛', text: '那便随我来。沿途的碎甲你且一枚枚挖出、认明——「时光年月、朝夕昼夜、光头面眼耳口鼻、手足身心骨皮毛发齿舌、肩胸腰腿脚指」这些，都在这一程里。' },
        { speaker: '提示', kind: 'system', text: '任务更新：在第六章：古墟残灯中挖掘并发掘失语的甲骨碎片。每寻回一枚，阿烛便信你一分。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-001',
      checkpoint: true,
    },
    {
      id: 'chapter-6-ruins-lamp-seek-001',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '断柱下的土层里沉着微光。挖出「时」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-001',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-001',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识时字', detail: '观察骨纹，认出这是「时」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-002',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-002',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '残阶旁的土层里沉着微光。挖出「分」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-002',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-002',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识分字', detail: '观察骨纹，认出这是「分」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-003',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-003',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '碎陶堆中的土层里沉着微光。挖出「刻」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-003',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-003',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识刻字', detail: '观察骨纹，认出这是「刻」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-004',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-004',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '半塌祭台的土层里沉着微光。挖出「年」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-004',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-004',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识年字', detail: '观察骨纹，认出这是「年」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-005',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-005',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '焦木深处的土层里沉着微光。挖出「岁」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-005',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-005',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识岁字', detail: '观察骨纹，认出这是「岁」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-006',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-006',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '尘封廊庑的土层里沉着微光。挖出「朝」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-006',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-006',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识朝字', detail: '观察骨纹，认出这是「朝」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-007',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-007',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '倾颓门扉的土层里沉着微光。挖出「夕」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-007',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-007',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识夕字', detail: '观察骨纹，认出这是「夕」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-008',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-008',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '枯井沿的土层里沉着微光。挖出「昼」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-008',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-008',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识昼字', detail: '观察骨纹，认出这是「昼」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-009',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-009',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '坍墙夹缝的土层里沉着微光。挖出「夜」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-009',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-009',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识夜字', detail: '观察骨纹，认出这是「夜」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-010',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-010',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '祭器残片的土层里沉着微光。挖出「光」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-010',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-010',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识光字', detail: '观察骨纹，认出这是「光」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-011',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-011',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '幽暗甬道的土层里沉着微光。挖出「头」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-011',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-011',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识头字', detail: '观察骨纹，认出这是「头」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-012',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-012',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '漏顶天井的土层里沉着微光。挖出「面」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-012',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-012',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识面字', detail: '观察骨纹，认出这是「面」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-013',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-013',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '荒庭中央的土层里沉着微光。挖出「眼」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-013',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-013',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识眼字', detail: '观察骨纹，认出这是「眼」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-014',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-014',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '残碑之侧的土层里沉着微光。挖出「耳」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-014',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-014',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识耳字', detail: '观察骨纹，认出这是「耳」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-015',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-015',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '兽骨堆里的土层里沉着微光。挖出「口」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-015',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-015',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识口字', detail: '观察骨纹，认出这是「口」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-016',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-016',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '熄灯石龛的土层里沉着微光。挖出「鼻」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-016',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-016',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识鼻字', detail: '观察骨纹，认出这是「鼻」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-midstream',
    },
    {
      id: 'chapter-6-ruins-lamp-midstream',
      chapterId: CHAPTER_SIX_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '半数碎甲归位的刹那，阿烛一直绷着的神色松了下来。这一程的脉络，第一次在你们之间连成线。' },
        { speaker: '灯匠·阿烛', text: '原以为这桩「废墟点灯」只是我一家的事。可你挖出的骨片，真的一枚枚在我眼前活了——这回我信你。' },
        { speaker: '神秘低语', text: '……骨归其序，事乃成章……' },
        { speaker: '贞人师', text: '中段已过，阿烛终肯托付。继续寻回余下的碎甲，这一程的真相便近了。' },
        { speaker: '提示', kind: 'system', text: '中段：16字已聚，阿烛托付于你。继续入深处，寻回余下碎甲。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-017',
      checkpoint: true,
    },
    {
      id: 'chapter-6-ruins-lamp-seek-017',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '断柱下的土层里沉着微光。挖出「手」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-017',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-017',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识手字', detail: '观察骨纹，认出这是「手」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-018',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-018',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '残阶旁的土层里沉着微光。挖出「足」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-018',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-018',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识足字', detail: '观察骨纹，认出这是「足」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-019',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-019',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '碎陶堆中的土层里沉着微光。挖出「心」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-019',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-019',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识心字', detail: '观察骨纹，认出这是「心」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-020',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-020',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '半塌祭台的土层里沉着微光。挖出「身」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-020',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-020',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识身字', detail: '观察骨纹，认出这是「身」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-021',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-021',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '焦木深处的土层里沉着微光。挖出「骨」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-021',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-021',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识骨字', detail: '观察骨纹，认出这是「骨」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-022',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-022',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '尘封廊庑的土层里沉着微光。挖出「皮」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-022',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-022',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识皮字', detail: '观察骨纹，认出这是「皮」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-023',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-023',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '倾颓门扉的土层里沉着微光。挖出「毛」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-023',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-023',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识毛字', detail: '观察骨纹，认出这是「毛」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-024',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-024',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '枯井沿的土层里沉着微光。挖出「发」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-024',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-024',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识发字', detail: '观察骨纹，认出这是「发」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-025',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-025',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '坍墙夹缝的土层里沉着微光。挖出「齿」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-025',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-025',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识齿字', detail: '观察骨纹，认出这是「齿」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-026',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-026',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '祭器残片的土层里沉着微光。挖出「舌」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-026',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-026',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识舌字', detail: '观察骨纹，认出这是「舌」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-027',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-027',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '幽暗甬道的土层里沉着微光。挖出「肩」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-027',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-027',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识肩字', detail: '观察骨纹，认出这是「肩」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-028',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-028',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '漏顶天井的土层里沉着微光。挖出「胸」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-028',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-028',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识胸字', detail: '观察骨纹，认出这是「胸」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-029',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-029',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '荒庭中央的土层里沉着微光。挖出「腰」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-029',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-029',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识腰字', detail: '观察骨纹，认出这是「腰」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-030',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-030',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '残碑之侧的土层里沉着微光。挖出「腿」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-030',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-030',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识腿字', detail: '观察骨纹，认出这是「腿」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-031',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-031',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '兽骨堆里的土层里沉着微光。挖出「脚」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-031',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-031',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识脚字', detail: '观察骨纹，认出这是「脚」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-seek-032',
    },
    {
      id: 'chapter-6-ruins-lamp-seek-032',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 寻骨', detail: '熄灯石龛的土层里沉着微光。挖出「指」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-6-ruins-lamp-lesson-032',
    },
    {
      id: 'chapter-6-ruins-lamp-lesson-032',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 辨识指字', detail: '观察骨纹，认出这是「指」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-6-ruins-lamp-fragment-awakens',
    },
    {
      id: 'chapter-6-ruins-lamp-fragment-awakens',
      chapterId: CHAPTER_SIX_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '32枚废墟点灯碎甲在掌心排开。你按这一程的脉络理好，骨纹竟投出一道微光，照见阿烛要办之事的去向。' },
        { speaker: '神秘低语', text: '……废墟点灯毕，骨已成章……' },
        { speaker: '你', text: '原来这一程记下的不是死物，是「时光年月、朝夕昼夜、光头面眼耳口鼻、手足身心骨皮毛发齿舌、肩胸腰腿脚指」里活着的学问。它们齐了，去路才显在眼前。' },
        { speaker: '灯匠·阿烛', text: '我听不见金光里的声音，可骨片真的在你手里连成了路！守卜人，你果然是贞人师说的那个人。' },
        { speaker: '提示', kind: 'system', text: '获得：「时光年月、朝夕昼夜、光头面眼耳口鼻、手足身心骨皮毛发齿舌、肩胸腰腿脚指」32枚废墟点灯甲骨碎片。卜力已苏醒，可落为天意之辞。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-6-ruins-lamp-first-request',
    },
    {
      id: 'chapter-6-ruins-lamp-first-request',
      chapterId: CHAPTER_SIX_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '32枚碎甲归位，阿烛这一桩「废墟点灯」的脉络已清。可尚有未解的悬疑，要借卜力一问。' },
        { speaker: '灯匠·阿烛', text: '守卜人，这32枚甲骨记下的事，我已信了八九分。可还有三桩悬案，能用这些字卜一卜么？' },
        { speaker: '你', text: '（你斟酌：三问牵连，当一卜接一卜地解。取过一枚甲骨——先卜其一，其余的，且待兆纹引你去看。）' },
        { speaker: '贞人师', text: '去吧。以这一程的卜力，为阿烛卜算「灯序之数、点亮之序、残灯所指」三桩悬案。每解一桩，卜力便积一分。' },
        { speaker: '提示', kind: 'system', text: '守卜任务开启（第一轮）：为灯匠·阿烛卜算「灯序之数」，留意兆纹里多出的那道裂纹。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-6-ruins-lamp-enter-temple',
      checkpoint: true,
    },
    {
      id: 'chapter-6-ruins-lamp-enter-temple',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第六章：古墟残灯 · 问卜', detail: '随灯匠·阿烛返回宗庙内殿，准备以本章甲骨问卜。', targetX: 0, targetY: 1010, targetRadius: 110 },
      completeOn: 'temple-entered',
      nextStepId: 'chapter-6-ruins-lamp-take-seat',
    },
    {
      id: 'chapter-6-ruins-lamp-take-seat',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '问卜 · 入席', detail: '走到内殿占卜席前，点击“坐下”，听灯匠·阿烛讲清要卜之事。' },
      completeOn: 'temple-seat-reached',
      nextStepId: 'chapter-6-ruins-lamp-divination-1',
    },
    {
      id: 'chapter-6-ruins-lamp-divination-1',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第1轮问卜 · 灯序之数', detail: '灯匠·阿烛请你以本章甲骨卜算「灯序之数」。' },
      completeOn: 'divination-completed',
      nextStepId: 'chapter-6-ruins-lamp-divination-2',
      checkpoint: true,
    },
    {
      id: 'chapter-6-ruins-lamp-divination-2',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第2轮问卜 · 点亮之序', detail: '灯匠·阿烛请你以本章甲骨卜算「点亮之序」。' },
      completeOn: 'divination-completed',
      nextStepId: 'chapter-6-ruins-lamp-divination-3',
      checkpoint: true,
    },
    {
      id: 'chapter-6-ruins-lamp-divination-3',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '第3轮问卜 · 残灯所指', detail: '灯匠·阿烛请你以本章甲骨卜算「残灯所指」。' },
      completeOn: 'divination-completed',
      nextStepId: 'chapter-6-ruins-lamp-leave-seat',
    },
    {
      id: 'chapter-6-ruins-lamp-leave-seat',
      chapterId: CHAPTER_SIX_ID,
      objective: { title: '异常兆纹', detail: '完成三轮占卜后起身，查看甲骨额外显出的那道裂纹。' },
      completeOn: 'result-confirmed',
      nextStepId: 'chapter-6-ruins-lamp-clue-revealed',
    },
    {
      id: 'chapter-6-ruins-lamp-clue-revealed',
      chapterId: CHAPTER_SIX_ID,
      dialogue: [
        { speaker: '灯匠·阿烛', text: '原来「灯序之数、点亮之序、残灯所指」三问，兆纹都指向下一处——残灯依次亮起，照出废墟深处一卷将焚的典册——错册余火，待你去辨。' },
        { speaker: '旁白', kind: 'narration', text: '三卜既毕，兆纹并未熄灭。几道裂纹缓缓延伸，竟越过这一程，指向「错册余火」。' },
        { speaker: '神秘低语', text: '……错册余火……有骨……待人相续……' },
        { speaker: '贞人师', text: '三轮卜辞彼此牵引，这道裂纹拐出了这一程——下一处碎甲，在「错册余火」里。' },
        { speaker: '提示', kind: 'system', text: '第六章：古墟残灯完成。获得线索「错册余火」，下一章已开启。' },
      ],
      completeOn: 'dialogue-completed',
      checkpoint: true,
    },
  ],
};
