import { StoryChapterDefinition } from './StoryTypes';

// 第九章：重续通天之契
// 终章抉择·分支结局（重铸神甲 / 不依赖神谕），完成即主线全通→触发拾遗渐进揭示
// 字量 48，全部来自 ChapterCharMap 第 9 章分配（编号 203~250）。
export const CHAPTER_NINE_ID = 'chapter-9-renew-covenant';
// 大卜·阿圭 站位（坐标待 Cocos 微调）；进章传送落其旁。

export const CHAPTER_NINE_FRAGMENT_CARDS = [
  { seekStepId: 'chapter-9-renew-covenant-seek-001', lessonStepId: 'chapter-9-renew-covenant-lesson-001', cardId: 'catalog-u6e38', character: '游' },
  { seekStepId: 'chapter-9-renew-covenant-seek-002', lessonStepId: 'chapter-9-renew-covenant-lesson-002', cardId: 'catalog-u722c', character: '爬' },
  { seekStepId: 'chapter-9-renew-covenant-seek-003', lessonStepId: 'chapter-9-renew-covenant-lesson-003', cardId: 'catalog-u770b', character: '看' },
  { seekStepId: 'chapter-9-renew-covenant-seek-004', lessonStepId: 'chapter-9-renew-covenant-lesson-004', cardId: 'catalog-u542c', character: '听' },
  { seekStepId: 'chapter-9-renew-covenant-seek-005', lessonStepId: 'chapter-9-renew-covenant-lesson-005', cardId: 'catalog-u8bf4', character: '说' },
  { seekStepId: 'chapter-9-renew-covenant-seek-006', lessonStepId: 'chapter-9-renew-covenant-lesson-006', cardId: 'catalog-u8bfb', character: '读' },
  { seekStepId: 'chapter-9-renew-covenant-seek-007', lessonStepId: 'chapter-9-renew-covenant-lesson-007', cardId: 'catalog-u5199', character: '写' },
  { seekStepId: 'chapter-9-renew-covenant-seek-008', lessonStepId: 'chapter-9-renew-covenant-lesson-008', cardId: 'catalog-u5ff5', character: '念' },
  { seekStepId: 'chapter-9-renew-covenant-seek-009', lessonStepId: 'chapter-9-renew-covenant-lesson-009', cardId: 'catalog-u558a', character: '喊' },
  { seekStepId: 'chapter-9-renew-covenant-seek-010', lessonStepId: 'chapter-9-renew-covenant-lesson-010', cardId: 'catalog-u53eb', character: '叫' },
  { seekStepId: 'chapter-9-renew-covenant-seek-011', lessonStepId: 'chapter-9-renew-covenant-lesson-011', cardId: 'catalog-u7b11', character: '笑' },
  { seekStepId: 'chapter-9-renew-covenant-seek-012', lessonStepId: 'chapter-9-renew-covenant-lesson-012', cardId: 'catalog-u54ed', character: '哭' },
  { seekStepId: 'chapter-9-renew-covenant-seek-013', lessonStepId: 'chapter-9-renew-covenant-lesson-013', cardId: 'catalog-u5403', character: '吃' },
  { seekStepId: 'chapter-9-renew-covenant-seek-014', lessonStepId: 'chapter-9-renew-covenant-lesson-014', cardId: 'catalog-u559d', character: '喝' },
  { seekStepId: 'chapter-9-renew-covenant-seek-015', lessonStepId: 'chapter-9-renew-covenant-lesson-015', cardId: 'catalog-u7761', character: '睡' },
  { seekStepId: 'chapter-9-renew-covenant-seek-016', lessonStepId: 'chapter-9-renew-covenant-lesson-016', cardId: 'catalog-u6d17', character: '洗' },
  { seekStepId: 'chapter-9-renew-covenant-seek-017', lessonStepId: 'chapter-9-renew-covenant-lesson-017', cardId: 'catalog-u626b', character: '扫' },
  { seekStepId: 'chapter-9-renew-covenant-seek-018', lessonStepId: 'chapter-9-renew-covenant-lesson-018', cardId: 'catalog-u64e6', character: '擦' },
  { seekStepId: 'chapter-9-renew-covenant-seek-019', lessonStepId: 'chapter-9-renew-covenant-lesson-019', cardId: 'catalog-u5f00', character: '开' },
  { seekStepId: 'chapter-9-renew-covenant-seek-020', lessonStepId: 'chapter-9-renew-covenant-lesson-020', cardId: 'catalog-u5173', character: '关' },
  { seekStepId: 'chapter-9-renew-covenant-seek-021', lessonStepId: 'chapter-9-renew-covenant-lesson-021', cardId: 'catalog-u62ff', character: '拿' },
  { seekStepId: 'chapter-9-renew-covenant-seek-022', lessonStepId: 'chapter-9-renew-covenant-lesson-022', cardId: 'catalog-u653e', character: '放' },
  { seekStepId: 'chapter-9-renew-covenant-seek-023', lessonStepId: 'chapter-9-renew-covenant-lesson-023', cardId: 'catalog-u6765', character: '来' },
  { seekStepId: 'chapter-9-renew-covenant-seek-024', lessonStepId: 'chapter-9-renew-covenant-lesson-024', cardId: 'catalog-u53bb', character: '去' },
  { seekStepId: 'chapter-9-renew-covenant-seek-025', lessonStepId: 'chapter-9-renew-covenant-lesson-025', cardId: 'catalog-u8fdb', character: '进' },
  { seekStepId: 'chapter-9-renew-covenant-seek-026', lessonStepId: 'chapter-9-renew-covenant-lesson-026', cardId: 'catalog-u51fa', character: '出' },
  { seekStepId: 'chapter-9-renew-covenant-seek-027', lessonStepId: 'chapter-9-renew-covenant-lesson-027', cardId: 'catalog-u56de', character: '回' },
  { seekStepId: 'chapter-9-renew-covenant-seek-028', lessonStepId: 'chapter-9-renew-covenant-lesson-028', cardId: 'catalog-u5230', character: '到' },
  { seekStepId: 'chapter-9-renew-covenant-seek-029', lessonStepId: 'chapter-9-renew-covenant-lesson-029', cardId: 'catalog-u5f80', character: '往' },
  { seekStepId: 'chapter-9-renew-covenant-seek-030', lessonStepId: 'chapter-9-renew-covenant-lesson-030', cardId: 'catalog-u767b', character: '登' },
  { seekStepId: 'chapter-9-renew-covenant-seek-031', lessonStepId: 'chapter-9-renew-covenant-lesson-031', cardId: 'catalog-u6500', character: '攀' },
  { seekStepId: 'chapter-9-renew-covenant-seek-032', lessonStepId: 'chapter-9-renew-covenant-lesson-032', cardId: 'catalog-u7231', character: '爱' },
  { seekStepId: 'chapter-9-renew-covenant-seek-033', lessonStepId: 'chapter-9-renew-covenant-lesson-033', cardId: 'catalog-u559c', character: '喜' },
  { seekStepId: 'chapter-9-renew-covenant-seek-034', lessonStepId: 'chapter-9-renew-covenant-lesson-034', cardId: 'catalog-u6012', character: '怒' },
  { seekStepId: 'chapter-9-renew-covenant-seek-035', lessonStepId: 'chapter-9-renew-covenant-lesson-035', cardId: 'catalog-u60b2', character: '悲' },
  { seekStepId: 'chapter-9-renew-covenant-seek-036', lessonStepId: 'chapter-9-renew-covenant-lesson-036', cardId: 'catalog-u6101', character: '愁' },
  { seekStepId: 'chapter-9-renew-covenant-seek-037', lessonStepId: 'chapter-9-renew-covenant-lesson-037', cardId: 'catalog-u601d', character: '思' },
  { seekStepId: 'chapter-9-renew-covenant-seek-038', lessonStepId: 'chapter-9-renew-covenant-lesson-038', cardId: 'catalog-u60f3', character: '想' },
  { seekStepId: 'chapter-9-renew-covenant-seek-039', lessonStepId: 'chapter-9-renew-covenant-lesson-039', cardId: 'catalog-u77e5', character: '知' },
  { seekStepId: 'chapter-9-renew-covenant-seek-040', lessonStepId: 'chapter-9-renew-covenant-lesson-040', cardId: 'catalog-u61c2', character: '懂' },
  { seekStepId: 'chapter-9-renew-covenant-seek-041', lessonStepId: 'chapter-9-renew-covenant-lesson-041', cardId: 'catalog-u8bb0', character: '记' },
  { seekStepId: 'chapter-9-renew-covenant-seek-042', lessonStepId: 'chapter-9-renew-covenant-lesson-042', cardId: 'catalog-u597d', character: '好' },
  { seekStepId: 'chapter-9-renew-covenant-seek-043', lessonStepId: 'chapter-9-renew-covenant-lesson-043', cardId: 'catalog-u574f', character: '坏' },
  { seekStepId: 'chapter-9-renew-covenant-seek-044', lessonStepId: 'chapter-9-renew-covenant-lesson-044', cardId: 'catalog-u771f', character: '真' },
  { seekStepId: 'chapter-9-renew-covenant-seek-045', lessonStepId: 'chapter-9-renew-covenant-lesson-045', cardId: 'catalog-u5047', character: '假' },
  { seekStepId: 'chapter-9-renew-covenant-seek-046', lessonStepId: 'chapter-9-renew-covenant-lesson-046', cardId: 'catalog-u65b0', character: '新' },
  { seekStepId: 'chapter-9-renew-covenant-seek-047', lessonStepId: 'chapter-9-renew-covenant-lesson-047', cardId: 'catalog-u65e7', character: '旧' },
  { seekStepId: 'chapter-9-renew-covenant-seek-048', lessonStepId: 'chapter-9-renew-covenant-lesson-048', cardId: 'catalog-u9ad8', character: '高' },
] as const;

export const chapterNineDefinition: StoryChapterDefinition = {
  id: CHAPTER_NINE_ID,
  title: '第九章：重续通天之契',
  firstStepId: 'chapter-9-renew-covenant-opening',
  steps: [
    {
      id: 'chapter-9-renew-covenant-opening',
      chapterId: CHAPTER_NINE_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '三证齐聚，沉重的陵门轰然洞开。最深处，一具指天而立的卜骨静静等候，四壁裂纹如星河流转。执掌通天之礼的大卜·阿圭在此相候——重续通天之契，只在此一举。' },
        { speaker: '贞人师', text: '这一程在陵寝最深、卜骨之前、通天坛上。大卜·阿圭守着一桩要紧的事，需你以甲骨一一卜算。' },
        { speaker: '大卜·阿圭', text: '守卜人，我名阿圭。此去事繁，你若相助，便以你卜出的甲骨引我趋吉辨伪——如何？' },
        { speaker: '提示', kind: 'system', text: '第九章：重续通天之契开启。当前目标：寻到大卜·阿圭，在这一程各处寻回失语的终章抉择甲骨碎片。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-9-renew-covenant-reach-npc',
      checkpoint: true,
    },
    {
      id: 'chapter-9-renew-covenant-reach-npc',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 启程', detail: '走到大卜·阿圭身边，听他（她）讲清这一程要卜的事。', storyLocationId: 'chapter-9-city-npc', targetRadius: 200 },
      completeOn: 'npc-reached',
      nextStepId: 'chapter-9-renew-covenant-npc-dialogue',
    },
    {
      id: 'chapter-9-renew-covenant-npc-dialogue',
      chapterId: CHAPTER_NINE_ID,
      dialogue: [
        { speaker: '大卜·阿圭', text: '我这一程要办的，是「终章抉择」。这一带散着48枚记着这事的老刻，自打天意断了就再没响过。' },
        { speaker: '你', text: '我不是来指路，是来听骨。你若信我，便一枚枚唤醒它们，兆纹自会引我们看清明细。' },
        { speaker: '大卜·阿圭', text: '那便随我来。沿途的碎甲你且一枚枚挖出、认明——「游爬看听说说读念喊叫笑哭吃喝睡洗扫擦开关拿放来去进出回到往登攀爱喜怒悲愁思想知懂记好好坏真假新旧高」这些，都在这一程里。' },
        { speaker: '提示', kind: 'system', text: '任务更新：在第九章：重续通天之契中挖掘并发掘失语的甲骨碎片。每寻回一枚，阿圭便信你一分。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-001',
      checkpoint: true,
    },
    {
      id: 'chapter-9-renew-covenant-seek-001',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '登天石阶的土层里沉着微光。挖出「游」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-001',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-001',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识游字', detail: '观察骨纹，认出这是「游」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-002',
    },
    {
      id: 'chapter-9-renew-covenant-seek-002',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '攀云栈道的土层里沉着微光。挖出「爬」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-002',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-002',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识爬字', detail: '观察骨纹，认出这是「爬」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-003',
    },
    {
      id: 'chapter-9-renew-covenant-seek-003',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '游观之台的土层里沉着微光。挖出「看」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-003',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-003',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识看字', detail: '观察骨纹，认出这是「看」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-004',
    },
    {
      id: 'chapter-9-renew-covenant-seek-004',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '爬行甬道的土层里沉着微光。挖出「听」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-004',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-004',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识听字', detail: '观察骨纹，认出这是「听」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-005',
    },
    {
      id: 'chapter-9-renew-covenant-seek-005',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '看礼之位的土层里沉着微光。挖出「说」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-005',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-005',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识说字', detail: '观察骨纹，认出这是「说」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-006',
    },
    {
      id: 'chapter-9-renew-covenant-seek-006',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '听卜之席的土层里沉着微光。挖出「读」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-006',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-006',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识读字', detail: '观察骨纹，认出这是「读」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-007',
    },
    {
      id: 'chapter-9-renew-covenant-seek-007',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '说辞之简的土层里沉着微光。挖出「写」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-007',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-007',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识写字', detail: '观察骨纹，认出这是「写」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-008',
    },
    {
      id: 'chapter-9-renew-covenant-seek-008',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '读铭之壁的土层里沉着微光。挖出「念」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-008',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-008',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识念字', detail: '观察骨纹，认出这是「念」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-009',
    },
    {
      id: 'chapter-9-renew-covenant-seek-009',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '写辞之案的土层里沉着微光。挖出「喊」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-009',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-009',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识喊字', detail: '观察骨纹，认出这是「喊」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-010',
    },
    {
      id: 'chapter-9-renew-covenant-seek-010',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '念诵之坛的土层里沉着微光。挖出「叫」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-010',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-010',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识叫字', detail: '观察骨纹，认出这是「叫」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-011',
    },
    {
      id: 'chapter-9-renew-covenant-seek-011',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '呼喊之口的土层里沉着微光。挖出「笑」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-011',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-011',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识笑字', detail: '观察骨纹，认出这是「笑」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-012',
    },
    {
      id: 'chapter-9-renew-covenant-seek-012',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '叫唤之钟的土层里沉着微光。挖出「哭」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-012',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-012',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识哭字', detail: '观察骨纹，认出这是「哭」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-013',
    },
    {
      id: 'chapter-9-renew-covenant-seek-013',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '笑语回廊的土层里沉着微光。挖出「吃」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-013',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-013',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识吃字', detail: '观察骨纹，认出这是「吃」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-014',
    },
    {
      id: 'chapter-9-renew-covenant-seek-014',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '哭诉之庭的土层里沉着微光。挖出「喝」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-014',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-014',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识喝字', detail: '观察骨纹，认出这是「喝」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-015',
    },
    {
      id: 'chapter-9-renew-covenant-seek-015',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '食之祭案的土层里沉着微光。挖出「睡」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-015',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-015',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识睡字', detail: '观察骨纹，认出这是「睡」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-016',
    },
    {
      id: 'chapter-9-renew-covenant-seek-016',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '饮之礼器的土层里沉着微光。挖出「洗」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-016',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-016',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识洗字', detail: '观察骨纹，认出这是「洗」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-017',
    },
    {
      id: 'chapter-9-renew-covenant-seek-017',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '寐卧之榻的土层里沉着微光。挖出「扫」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-017',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-017',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识扫字', detail: '观察骨纹，认出这是「扫」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-018',
    },
    {
      id: 'chapter-9-renew-covenant-seek-018',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '盥洗之盘的土层里沉着微光。挖出「擦」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-018',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-018',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识擦字', detail: '观察骨纹，认出这是「擦」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-019',
    },
    {
      id: 'chapter-9-renew-covenant-seek-019',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '拂尘之帚的土层里沉着微光。挖出「开」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-019',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-019',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识开字', detail: '观察骨纹，认出这是「开」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-020',
    },
    {
      id: 'chapter-9-renew-covenant-seek-020',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '擦拭之巾的土层里沉着微光。挖出「关」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-020',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-020',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识关字', detail: '观察骨纹，认出这是「关」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-021',
    },
    {
      id: 'chapter-9-renew-covenant-seek-021',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '开户之枢的土层里沉着微光。挖出「拿」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-021',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-021',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识拿字', detail: '观察骨纹，认出这是「拿」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-022',
    },
    {
      id: 'chapter-9-renew-covenant-seek-022',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '闭户之栓的土层里沉着微光。挖出「放」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-022',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-022',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识放字', detail: '观察骨纹，认出这是「放」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-023',
    },
    {
      id: 'chapter-9-renew-covenant-seek-023',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '持物之手的土层里沉着微光。挖出「来」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-023',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-023',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识来字', detail: '观察骨纹，认出这是「来」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-024',
    },
    {
      id: 'chapter-9-renew-covenant-seek-024',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '安放之格的土层里沉着微光。挖出「去」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-024',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-024',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识去字', detail: '观察骨纹，认出这是「去」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-midstream',
    },
    {
      id: 'chapter-9-renew-covenant-midstream',
      chapterId: CHAPTER_NINE_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '半数碎甲归位的刹那，阿圭一直绷着的神色松了下来。这一程的脉络，第一次在你们之间连成线。' },
        { speaker: '大卜·阿圭', text: '原以为这桩「终章抉择」只是我一家的事。可你挖出的骨片，真的一枚枚在我眼前活了——这回我信你。' },
        { speaker: '神秘低语', text: '……骨归其序，事乃成章……' },
        { speaker: '贞人师', text: '中段已过，阿圭终肯托付。继续寻回余下的碎甲，这一程的真相便近了。' },
        { speaker: '提示', kind: 'system', text: '中段：24字已聚，阿圭托付于你。继续入深处，寻回余下碎甲。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-025',
      checkpoint: true,
    },
    {
      id: 'chapter-9-renew-covenant-seek-025',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '来迎之阶的土层里沉着微光。挖出「进」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-025',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-025',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识进字', detail: '观察骨纹，认出这是「进」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-026',
    },
    {
      id: 'chapter-9-renew-covenant-seek-026',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '去往之径的土层里沉着微光。挖出「出」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-026',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-026',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识出字', detail: '观察骨纹，认出这是「出」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-027',
    },
    {
      id: 'chapter-9-renew-covenant-seek-027',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '进谒之陛的土层里沉着微光。挖出「回」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-027',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-027',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识回字', detail: '观察骨纹，认出这是「回」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-028',
    },
    {
      id: 'chapter-9-renew-covenant-seek-028',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '出巡之道的土层里沉着微光。挖出「到」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-028',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-028',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识到字', detail: '观察骨纹，认出这是「到」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-029',
    },
    {
      id: 'chapter-9-renew-covenant-seek-029',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '回銮之路的土层里沉着微光。挖出「往」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-029',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-029',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识往字', detail: '观察骨纹，认出这是「往」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-030',
    },
    {
      id: 'chapter-9-renew-covenant-seek-030',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '到达之碑的土层里沉着微光。挖出「登」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-030',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-030',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识登字', detail: '观察骨纹，认出这是「登」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-031',
    },
    {
      id: 'chapter-9-renew-covenant-seek-031',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '往还之辙的土层里沉着微光。挖出「攀」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-031',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-031',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识攀字', detail: '观察骨纹，认出这是「攀」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-032',
    },
    {
      id: 'chapter-9-renew-covenant-seek-032',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '登陟之坡的土层里沉着微光。挖出「爱」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-032',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-032',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识爱字', detail: '观察骨纹，认出这是「爱」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-033',
    },
    {
      id: 'chapter-9-renew-covenant-seek-033',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '攀缘之索的土层里沉着微光。挖出「喜」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-033',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-033',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识喜字', detail: '观察骨纹，认出这是「喜」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-034',
    },
    {
      id: 'chapter-9-renew-covenant-seek-034',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '爱慕之坛的土层里沉着微光。挖出「怒」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-034',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-034',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识怒字', detail: '观察骨纹，认出这是「怒」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-035',
    },
    {
      id: 'chapter-9-renew-covenant-seek-035',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '喜庆之庭的土层里沉着微光。挖出「悲」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-035',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-035',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识悲字', detail: '观察骨纹，认出这是「悲」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-036',
    },
    {
      id: 'chapter-9-renew-covenant-seek-036',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '怒目之像的土层里沉着微光。挖出「愁」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-036',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-036',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识愁字', detail: '观察骨纹，认出这是「愁」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-037',
    },
    {
      id: 'chapter-9-renew-covenant-seek-037',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '悲怆之窟的土层里沉着微光。挖出「思」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-037',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-037',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识思字', detail: '观察骨纹，认出这是「思」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-038',
    },
    {
      id: 'chapter-9-renew-covenant-seek-038',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '愁云之顶的土层里沉着微光。挖出「想」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-038',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-038',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识想字', detail: '观察骨纹，认出这是「想」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-039',
    },
    {
      id: 'chapter-9-renew-covenant-seek-039',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '思悟之台的土层里沉着微光。挖出「知」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-039',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-039',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识知字', detail: '观察骨纹，认出这是「知」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-040',
    },
    {
      id: 'chapter-9-renew-covenant-seek-040',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '知会之简的土层里沉着微光。挖出「懂」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-040',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-040',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识懂字', detail: '观察骨纹，认出这是「懂」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-041',
    },
    {
      id: 'chapter-9-renew-covenant-seek-041',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '懂契之印的土层里沉着微光。挖出「记」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-041',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-041',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识记字', detail: '观察骨纹，认出这是「记」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-042',
    },
    {
      id: 'chapter-9-renew-covenant-seek-042',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '记诵之册的土层里沉着微光。挖出「好」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-042',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-042',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识好字', detail: '观察骨纹，认出这是「好」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-043',
    },
    {
      id: 'chapter-9-renew-covenant-seek-043',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '好生之德的土层里沉着微光。挖出「坏」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-043',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-043',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识坏字', detail: '观察骨纹，认出这是「坏」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-044',
    },
    {
      id: 'chapter-9-renew-covenant-seek-044',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '坏败之戒的土层里沉着微光。挖出「真」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-044',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-044',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识真字', detail: '观察骨纹，认出这是「真」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-045',
    },
    {
      id: 'chapter-9-renew-covenant-seek-045',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '真契之玺的土层里沉着微光。挖出「假」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-045',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-045',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识假字', detail: '观察骨纹，认出这是「假」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-046',
    },
    {
      id: 'chapter-9-renew-covenant-seek-046',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '假伪之劾的土层里沉着微光。挖出「新」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-046',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-046',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识新字', detail: '观察骨纹，认出这是「新」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-047',
    },
    {
      id: 'chapter-9-renew-covenant-seek-047',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '新命之简的土层里沉着微光。挖出「旧」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-047',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-047',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识旧字', detail: '观察骨纹，认出这是「旧」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-seek-048',
    },
    {
      id: 'chapter-9-renew-covenant-seek-048',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 寻骨', detail: '旧誓之碑的土层里沉着微光。挖出「高」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-9-renew-covenant-lesson-048',
    },
    {
      id: 'chapter-9-renew-covenant-lesson-048',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 辨识高字', detail: '观察骨纹，认出这是「高」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-9-renew-covenant-fragment-awakens',
    },
    {
      id: 'chapter-9-renew-covenant-fragment-awakens',
      chapterId: CHAPTER_NINE_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '48枚终章抉择碎甲在掌心排开。你按这一程的脉络理好，骨纹竟投出一道微光，照见阿圭要办之事的去向。' },
        { speaker: '神秘低语', text: '……终章抉择毕，骨已成章……' },
        { speaker: '你', text: '原来这一程记下的不是死物，是「游爬看听说说读念喊叫笑哭吃喝睡洗扫擦开关拿放来去进出回到往登攀爱喜怒悲愁思想知懂记好好坏真假新旧高」里活着的学问。它们齐了，去路才显在眼前。' },
        { speaker: '大卜·阿圭', text: '我听不见金光里的声音，可骨片真的在你手里连成了路！守卜人，你果然是贞人师说的那个人。' },
        { speaker: '提示', kind: 'system', text: '获得：「游爬看听说说读念喊叫笑哭吃喝睡洗扫擦开关拿放来去进出回到往登攀爱喜怒悲愁思想知懂记好好坏真假新旧高」48枚终章抉择甲骨碎片。卜力已苏醒，可落为天意之辞。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-9-renew-covenant-first-request',
    },
    {
      id: 'chapter-9-renew-covenant-first-request',
      chapterId: CHAPTER_NINE_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '48枚碎甲归位，阿圭这一桩「终章抉择」的脉络已清。可尚有未解的悬疑，要借卜力一问。' },
        { speaker: '大卜·阿圭', text: '守卜人，这48枚甲骨记下的事，我已信了八九分。可还有三桩悬案，能用这些字卜一卜么？' },
        { speaker: '你', text: '（你斟酌：三问牵连，当一卜接一卜地解。取过一枚甲骨——先卜其一，其余的，且待兆纹引你去看。）' },
        { speaker: '贞人师', text: '去吧。以这一程的卜力，为阿圭卜算「重铸之择、神谕之问、通天之契」三桩悬案。每解一桩，卜力便积一分。' },
        { speaker: '提示', kind: 'system', text: '守卜任务开启（第一轮）：为大卜·阿圭卜算「重铸之择」，留意兆纹里多出的那道裂纹。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-9-renew-covenant-enter-temple',
      checkpoint: true,
    },
    {
      id: 'chapter-9-renew-covenant-enter-temple',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第九章：重续通天之契 · 问卜', detail: '随大卜·阿圭返回宗庙内殿，准备以本章甲骨问卜。', storyLocationId: 'city-divination-temple', targetRadius: 110 },
      completeOn: 'temple-entered',
      nextStepId: 'chapter-9-renew-covenant-take-seat',
    },
    {
      id: 'chapter-9-renew-covenant-take-seat',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '问卜 · 入席', detail: '走到内殿占卜席前，点击“坐下”，听大卜·阿圭讲清要卜之事。' },
      completeOn: 'temple-seat-reached',
      nextStepId: 'chapter-9-renew-covenant-divination-1',
    },
    {
      id: 'chapter-9-renew-covenant-divination-1',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第1轮问卜 · 重铸之择', detail: '大卜·阿圭请你以本章甲骨卜算「重铸之择」。' },
      completeOn: 'divination-completed',
      nextStepId: 'chapter-9-renew-covenant-divination-2',
      checkpoint: true,
    },
    {
      id: 'chapter-9-renew-covenant-divination-2',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第2轮问卜 · 神谕之问', detail: '大卜·阿圭请你以本章甲骨卜算「神谕之问」。' },
      completeOn: 'divination-completed',
      nextStepId: 'chapter-9-renew-covenant-divination-3',
      checkpoint: true,
    },
    {
      id: 'chapter-9-renew-covenant-divination-3',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '第3轮问卜 · 通天之契', detail: '大卜·阿圭请你以本章甲骨卜算「通天之契」。' },
      completeOn: 'divination-completed',
      nextStepId: 'chapter-9-renew-covenant-leave-seat',
    },
    {
      id: 'chapter-9-renew-covenant-leave-seat',
      chapterId: CHAPTER_NINE_ID,
      objective: { title: '异常兆纹', detail: '完成三轮占卜后起身，查看甲骨额外显出的那道裂纹。' },
      completeOn: 'result-confirmed',
      nextStepId: 'chapter-9-renew-covenant-clue-revealed',
    },
    {
      id: 'chapter-9-renew-covenant-clue-revealed',
      chapterId: CHAPTER_NINE_ID,
      dialogue: [
        { speaker: '大卜·阿圭', text: '原来「重铸之择、神谕之问、通天之契」三问，兆纹都指向下一处——通天之契既续，主线功成——散落殷墟各处的甲骨拾遗，将随你探索陆续浮现。' },
        { speaker: '旁白', kind: 'narration', text: '三卜既毕，兆纹并未熄灭。几道裂纹缓缓延伸，竟越过这一程，指向「拾遗现世」。' },
        { speaker: '神秘低语', text: '……拾遗现世……有骨……待人相续……' },
        { speaker: '贞人师', text: '三轮卜辞彼此牵引，这道裂纹拐出了这一程——下一处碎甲，在「拾遗现世」里。' },
        { speaker: '提示', kind: 'system', text: '第九章：重续通天之契完成。获得线索「拾遗现世」，下一章已开启。' },
      ],
      completeOn: 'dialogue-completed',
      checkpoint: true,
    },
  ],
};
