import { CHAPTER_ONE_ID } from './ChapterOne';
import { CHAPTER_TWO_ID } from './ChapterTwo';
import { CHAPTER_THREE_ID } from './ChapterThree';
import { CHAPTER_FOUR_ID } from './ChapterFour';
import { CHAPTER_FIVE_ID } from './ChapterFive';
import { CHAPTER_SIX_ID } from './ChapterSix';
import { CHAPTER_SEVEN_ID } from './ChapterSeven';
import { CHAPTER_EIGHT_ID } from './ChapterEight';
import { CHAPTER_NINE_ID } from './ChapterNine';

// 300 字目标字表 → 250 个主线剧情字 + 50 个甲骨拾遗字。
// 来源：《殷墟小卜官_300个甲骨文目标字表_最新修订版》。
// 第1章教学锁死 5 字（雨田水土地云，顺序同 ChapterOne.CHAPTER_ONE_FRAGMENT_CARDS）。
// 九章主线字量为 5/12/19/26/26/32/38/44/48，合计 250；编号 251—300 进入拾遗池。
// 主题自然贴合：字表本按语义分组编号（G1自然基础→G6性状礼祀），故前期章多自然/基础，后期章多性状/礼祀。
// existingCardId 来自游戏现有字库：手写卡用英文 id（rain/field/...），imported 卡用 catalog-u{unicode}；null 表示该字待补录（共157字）。
// 鱼、豆 为游戏原型残留的表外字，不在 300 目标表内，未参与本章分配。

export type CharGroup = 'G1' | 'G2' | 'G3' | 'G4' | 'G5' | 'G6';

export interface PlannedChar {
  num: string;
  char: string;
  group: CharGroup;
  existingCardId: string | null;
}

export interface ChapterCharPlan {
  chapterIndex: number;
  chapterId: string;
  title: string;
  charCount: number;
  chars: PlannedChar[];
}

export const CHAPTER_CHAR_PLANS: ChapterCharPlan[] = [
  {
    chapterIndex: 1,
    chapterId: CHAPTER_ONE_ID,
    title: '失语的甲骨',
    charCount: 5,
    chars: [
    { num: '036', char: '雨', group: 'G1', existingCardId: 'rain' },
    { num: '044', char: '田', group: 'G1', existingCardId: 'field' },
    { num: '038', char: '水', group: 'G1', existingCardId: 'catalog-u6c34' },
    { num: '040', char: '土', group: 'G1', existingCardId: 'catalog-u571f' },
    { num: '035', char: '云', group: 'G1', existingCardId: 'cloud-official' },
    ],
  },
  {
    chapterIndex: 2,
    chapterId: CHAPTER_TWO_ID,
    title: '河畔初兆',
    charCount: 12,
    chars: [
    { num: '047', char: '河', group: 'G1', existingCardId: 'river-official' },
    { num: '050', char: '泉', group: 'G1', existingCardId: 'catalog-u6cc9' },
    { num: '045', char: '沙', group: 'G1', existingCardId: 'catalog-u6c99' },
    { num: '043', char: '石', group: 'G1', existingCardId: 'catalog-u77f3' },
    { num: '042', char: '木', group: 'G1', existingCardId: 'catalog-u6728' },
    { num: '034', char: '风', group: 'G1', existingCardId: 'catalog-u98ce' },
    { num: '037', char: '山', group: 'G1', existingCardId: 'catalog-u5c71' },
    { num: '020', char: '上', group: 'G1', existingCardId: 'catalog-u4e0a' },
    { num: '021', char: '下', group: 'G1', existingCardId: 'catalog-u4e0b' },
    { num: '022', char: '左', group: 'G1', existingCardId: 'catalog-u5de6' },
    { num: '023', char: '右', group: 'G1', existingCardId: 'catalog-u53f3' },
    { num: '028', char: '中', group: 'G1', existingCardId: 'catalog-u4e2d' },
    ],
  },
  {
    chapterIndex: 3,
    chapterId: CHAPTER_THREE_ID,
    title: '逆流寻踪',
    charCount: 19,
    chars: [
    { num: '013', char: '万', group: 'G1', existingCardId: 'catalog-u4e07' },
    { num: '014', char: '人', group: 'G1', existingCardId: 'catalog-u4eba' },
    { num: '015', char: '民', group: 'G1', existingCardId: 'catalog-u6c11' },
    { num: '016', char: '大', group: 'G1', existingCardId: 'catalog-u5927' },
    { num: '017', char: '小', group: 'G1', existingCardId: 'catalog-u5c0f' },
    { num: '018', char: '多', group: 'G1', existingCardId: 'catalog-u591a' },
    { num: '019', char: '少', group: 'G1', existingCardId: 'catalog-u5c11' },
    { num: '001', char: '一', group: 'G1', existingCardId: 'catalog-u4e00' },
    { num: '002', char: '二', group: 'G1', existingCardId: 'catalog-u4e8c' },
    { num: '003', char: '三', group: 'G1', existingCardId: 'catalog-u4e09' },
    { num: '004', char: '四', group: 'G1', existingCardId: 'catalog-u56db' },
    { num: '024', char: '前', group: 'G1', existingCardId: 'catalog-u524d' },
    { num: '025', char: '后', group: 'G1', existingCardId: 'catalog-u540e' },
    { num: '026', char: '里', group: 'G1', existingCardId: 'catalog-u91cc' },
    { num: '027', char: '外', group: 'G1', existingCardId: 'catalog-u5916' },
    { num: '005', char: '五', group: 'G1', existingCardId: 'catalog-u4e94' },
    { num: '029', char: '天', group: 'G1', existingCardId: 'catalog-u5929' },
    { num: '030', char: '地', group: 'G1', existingCardId: 'catalog-u5730' },
    { num: '031', char: '日', group: 'G1', existingCardId: 'sun' },
    ],
  },
  {
    chapterIndex: 4,
    chapterId: CHAPTER_FOUR_ID,
    title: '山林迷径',
    charCount: 26,
    chars: [
    { num: '032', char: '月', group: 'G1', existingCardId: 'catalog-u6708' },
    { num: '033', char: '星', group: 'G1', existingCardId: 'star-official' },
    { num: '006', char: '六', group: 'G1', existingCardId: 'catalog-u516d' },
    { num: '007', char: '七', group: 'G1', existingCardId: 'catalog-u4e03' },
    { num: '008', char: '八', group: 'G1', existingCardId: 'catalog-u516b' },
    { num: '009', char: '九', group: 'G1', existingCardId: 'catalog-u4e5d' },
    { num: '010', char: '十', group: 'G1', existingCardId: 'catalog-u5341' },
    { num: '011', char: '百', group: 'G1', existingCardId: 'catalog-u767e' },
    { num: '012', char: '千', group: 'G1', existingCardId: 'catalog-u5343' },
    { num: '039', char: '火', group: 'G1', existingCardId: 'catalog-u706b' },
    { num: '041', char: '金', group: 'G1', existingCardId: 'catalog-u91d1' },
    { num: '046', char: '江', group: 'G1', existingCardId: null },
    { num: '048', char: '湖', group: 'G1', existingCardId: null },
    { num: '049', char: '海', group: 'G1', existingCardId: null },
    { num: '051', char: '父', group: 'G2', existingCardId: 'catalog-u7236' },
    { num: '052', char: '母', group: 'G2', existingCardId: 'catalog-u6bcd' },
    { num: '053', char: '爸', group: 'G2', existingCardId: null },
    { num: '054', char: '妈', group: 'G2', existingCardId: null },
    { num: '055', char: '爷', group: 'G2', existingCardId: null },
    { num: '056', char: '奶', group: 'G2', existingCardId: null },
    { num: '057', char: '哥', group: 'G2', existingCardId: null },
    { num: '058', char: '姐', group: 'G2', existingCardId: null },
    { num: '059', char: '弟', group: 'G2', existingCardId: 'catalog-u5f1f' },
    { num: '060', char: '妹', group: 'G2', existingCardId: 'catalog-u59b9' },
    { num: '061', char: '孩', group: 'G2', existingCardId: null },
    { num: '062', char: '儿', group: 'G2', existingCardId: 'catalog-u513f' },
    ],
  },
  {
    chapterIndex: 5,
    chapterId: CHAPTER_FIVE_ID,
    title: '护送归途',
    charCount: 26,
    chars: [
    { num: '063', char: '女', group: 'G2', existingCardId: 'catalog-u5973' },
    { num: '064', char: '老', group: 'G2', existingCardId: 'catalog-u8001' },
    { num: '065', char: '男', group: 'G2', existingCardId: 'catalog-u7537' },
    { num: '066', char: '你', group: 'G2', existingCardId: null },
    { num: '067', char: '我', group: 'G2', existingCardId: 'catalog-u6211' },
    { num: '068', char: '他', group: 'G2', existingCardId: null },
    { num: '069', char: '她', group: 'G2', existingCardId: null },
    { num: '070', char: '它', group: 'G2', existingCardId: 'catalog-u5b83' },
    { num: '071', char: '咱', group: 'G2', existingCardId: null },
    { num: '072', char: '们', group: 'G2', existingCardId: null },
    { num: '073', char: '谁', group: 'G2', existingCardId: null },
    { num: '074', char: '这', group: 'G2', existingCardId: null },
    { num: '075', char: '那', group: 'G2', existingCardId: null },
    { num: '076', char: '哪', group: 'G2', existingCardId: null },
    { num: '077', char: '今', group: 'G2', existingCardId: 'catalog-u4eca' },
    { num: '078', char: '明', group: 'G2', existingCardId: 'catalog-u660e' },
    { num: '079', char: '昨', group: 'G2', existingCardId: null },
    { num: '080', char: '春', group: 'G2', existingCardId: 'catalog-u6625' },
    { num: '081', char: '夏', group: 'G2', existingCardId: 'catalog-u590f' },
    { num: '082', char: '秋', group: 'G2', existingCardId: 'catalog-u79cb' },
    { num: '083', char: '冬', group: 'G2', existingCardId: null },
    { num: '084', char: '早', group: 'G2', existingCardId: 'catalog-u65e9' },
    { num: '085', char: '晚', group: 'G2', existingCardId: null },
    { num: '086', char: '午', group: 'G2', existingCardId: 'catalog-u5348' },
    { num: '087', char: '晨', group: 'G2', existingCardId: 'catalog-u6668' },
    { num: '088', char: '昏', group: 'G2', existingCardId: 'catalog-u660f' }
    ],
  },
  {
    chapterIndex: 6,
    chapterId: CHAPTER_SIX_ID,
    title: '古墟残灯',
    charCount: 32,
    chars: [
    { num: '089', char: '时', group: 'G2', existingCardId: null },
    { num: '090', char: '分', group: 'G2', existingCardId: 'catalog-u5206' },
    { num: '091', char: '刻', group: 'G2', existingCardId: 'catalog-u523b' },
    { num: '092', char: '年', group: 'G2', existingCardId: 'catalog-u5e74' },
    { num: '093', char: '岁', group: 'G2', existingCardId: 'catalog-u5c81' },
    { num: '094', char: '朝', group: 'G2', existingCardId: 'catalog-u671d' },
    { num: '095', char: '夕', group: 'G2', existingCardId: 'catalog-u5915' },
    { num: '096', char: '昼', group: 'G2', existingCardId: null },
    { num: '097', char: '夜', group: 'G2', existingCardId: 'catalog-u591c' },
    { num: '098', char: '光', group: 'G2', existingCardId: 'catalog-u5149' },
    { num: '099', char: '头', group: 'G2', existingCardId: 'catalog-u5934' },
    { num: '100', char: '面', group: 'G2', existingCardId: 'catalog-u9762' },
    { num: '101', char: '眼', group: 'G3', existingCardId: null },
    { num: '102', char: '耳', group: 'G3', existingCardId: 'catalog-u8033' },
    { num: '103', char: '口', group: 'G3', existingCardId: 'catalog-u53e3' },
    { num: '104', char: '鼻', group: 'G3', existingCardId: 'catalog-u9f3b' },
    { num: '105', char: '手', group: 'G3', existingCardId: null },
    { num: '106', char: '足', group: 'G3', existingCardId: null },
    { num: '107', char: '心', group: 'G3', existingCardId: 'catalog-u5fc3' },
    { num: '108', char: '身', group: 'G3', existingCardId: 'catalog-u8eab' },
    { num: '109', char: '骨', group: 'G3', existingCardId: 'catalog-u9aa8' },
    { num: '110', char: '皮', group: 'G3', existingCardId: 'catalog-u76ae' },
    { num: '111', char: '毛', group: 'G3', existingCardId: null },
    { num: '112', char: '发', group: 'G3', existingCardId: 'catalog-u53d1' },
    { num: '113', char: '齿', group: 'G3', existingCardId: null },
    { num: '114', char: '舌', group: 'G3', existingCardId: 'catalog-u820c' },
    { num: '115', char: '肩', group: 'G3', existingCardId: 'catalog-u80a9' },
    { num: '116', char: '胸', group: 'G3', existingCardId: null },
    { num: '117', char: '腰', group: 'G3', existingCardId: null },
    { num: '118', char: '腿', group: 'G3', existingCardId: null },
    { num: '119', char: '脚', group: 'G3', existingCardId: null },
    { num: '120', char: '指', group: 'G3', existingCardId: null }
    ],
  },
  {
    chapterIndex: 7,
    chapterId: CHAPTER_SEVEN_ID,
    title: '错册余火',
    charCount: 38,
    chars: [
    { num: '121', char: '掌', group: 'G3', existingCardId: null },
    { num: '122', char: '血', group: 'G3', existingCardId: 'catalog-u8840' },
    { num: '123', char: '汗', group: 'G3', existingCardId: null },
    { num: '124', char: '泪', group: 'G3', existingCardId: null },
    { num: '125', char: '气', group: 'G3', existingCardId: 'catalog-u6c14' },
    { num: '126', char: '声', group: 'G3', existingCardId: 'catalog-u58f0' },
    { num: '127', char: '音', group: 'G3', existingCardId: null },
    { num: '128', char: '饭', group: 'G3', existingCardId: null },
    { num: '129', char: '米', group: 'G3', existingCardId: 'catalog-u7c73' },
    { num: '130', char: '菜', group: 'G3', existingCardId: null },
    { num: '131', char: '瓜', group: 'G3', existingCardId: null },
    { num: '132', char: '果', group: 'G3', existingCardId: null },
    { num: '133', char: '茶', group: 'G3', existingCardId: null },
    { num: '134', char: '酒', group: 'G3', existingCardId: 'catalog-u9152' },
    { num: '135', char: '肉', group: 'G3', existingCardId: 'catalog-u8089' },
    { num: '136', char: '蛋', group: 'G3', existingCardId: null },
    { num: '137', char: '油', group: 'G3', existingCardId: null },
    { num: '138', char: '盐', group: 'G3', existingCardId: null },
    { num: '139', char: '糖', group: 'G3', existingCardId: null },
    { num: '140', char: '粥', group: 'G3', existingCardId: null },
    { num: '141', char: '饼', group: 'G3', existingCardId: null },
    { num: '142', char: '汤', group: 'G3', existingCardId: null },
    { num: '143', char: '字', group: 'G3', existingCardId: 'catalog-u5b57' },
    { num: '144', char: '麦', group: 'G3', existingCardId: null },
    { num: '145', char: '蔬', group: 'G3', existingCardId: null },
    { num: '146', char: '家', group: 'G3', existingCardId: 'catalog-u5bb6' },
    { num: '147', char: '房', group: 'G3', existingCardId: null },
    { num: '148', char: '屋', group: 'G3', existingCardId: null },
    { num: '149', char: '门', group: 'G3', existingCardId: 'catalog-u95e8' },
    { num: '150', char: '窗', group: 'G3', existingCardId: null },
    { num: '151', char: '墙', group: 'G4', existingCardId: 'catalog-u5899' },
    { num: '152', char: '桌', group: 'G4', existingCardId: null },
    { num: '153', char: '椅', group: 'G4', existingCardId: null },
    { num: '154', char: '床', group: 'G4', existingCardId: null },
    { num: '155', char: '灯', group: 'G4', existingCardId: null },
    { num: '156', char: '楼', group: 'G4', existingCardId: null },
    { num: '157', char: '契', group: 'G4', existingCardId: null },
    { num: '158', char: '院', group: 'G4', existingCardId: null }
    ],
  },
  {
    chapterIndex: 8,
    chapterId: CHAPTER_EIGHT_ID,
    title: '王陵三证',
    charCount: 44,
    chars: [
    { num: '159', char: '巷', group: 'G4', existingCardId: null },
    { num: '160', char: '街', group: 'G4', existingCardId: 'catalog-u8857' },
    { num: '161', char: '路', group: 'G4', existingCardId: null },
    { num: '162', char: '车', group: 'G4', existingCardId: null },
    { num: '163', char: '船', group: 'G4', existingCardId: null },
    { num: '164', char: '马', group: 'G4', existingCardId: 'catalog-u9a6c' },
    { num: '165', char: '桥', group: 'G4', existingCardId: null },
    { num: '166', char: '道', group: 'G4', existingCardId: 'catalog-u9053' },
    { num: '167', char: '坡', group: 'G4', existingCardId: null },
    { num: '168', char: '井', group: 'G4', existingCardId: 'catalog-u4e95' },
    { num: '169', char: '缸', group: 'G4', existingCardId: null },
    { num: '170', char: '盆', group: 'G4', existingCardId: 'catalog-u76c6' },
    { num: '171', char: '杯', group: 'G4', existingCardId: null },
    { num: '172', char: '碗', group: 'G4', existingCardId: null },
    { num: '173', char: '勺', group: 'G4', existingCardId: null },
    { num: '174', char: '筷', group: 'G4', existingCardId: null },
    { num: '175', char: '刀', group: 'G4', existingCardId: 'catalog-u5200' },
    { num: '176', char: '尺', group: 'G4', existingCardId: null },
    { num: '177', char: '笔', group: 'G4', existingCardId: null },
    { num: '178', char: '纸', group: 'G4', existingCardId: null },
    { num: '179', char: '书', group: 'G4', existingCardId: null },
    { num: '180', char: '本', group: 'G4', existingCardId: null },
    { num: '181', char: '烬', group: 'G4', existingCardId: null },
    { num: '182', char: '画', group: 'G4', existingCardId: 'catalog-u753b' },
    { num: '183', char: '图', group: 'G4', existingCardId: null },
    { num: '184', char: '册', group: 'G4', existingCardId: null },
    { num: '185', char: '校', group: 'G4', existingCardId: null },
    { num: '186', char: '学', group: 'G4', existingCardId: 'catalog-u5b66' },
    { num: '187', char: '师', group: 'G4', existingCardId: null },
    { num: '188', char: '生', group: 'G4', existingCardId: 'catalog-u751f' },
    { num: '189', char: '班', group: 'G4', existingCardId: null },
    { num: '190', char: '课', group: 'G4', existingCardId: null },
    { num: '191', char: '文', group: 'G4', existingCardId: 'catalog-u6587' },
    { num: '192', char: '数', group: 'G4', existingCardId: null },
    { num: '193', char: '语', group: 'G4', existingCardId: null },
    { num: '194', char: '英', group: 'G4', existingCardId: null },
    { num: '195', char: '走', group: 'G4', existingCardId: 'catalog-u8d70' },
    { num: '196', char: '跑', group: 'G4', existingCardId: null },
    { num: '197', char: '跳', group: 'G4', existingCardId: null },
    { num: '198', char: '站', group: 'G4', existingCardId: null },
    { num: '199', char: '坐', group: 'G4', existingCardId: 'catalog-u5750' },
    { num: '200', char: '卧', group: 'G4', existingCardId: null },
    { num: '201', char: '行', group: 'G5', existingCardId: 'catalog-u884c' },
    { num: '202', char: '飞', group: 'G5', existingCardId: null }
    ],
  },
  {
    chapterIndex: 9,
    chapterId: CHAPTER_NINE_ID,
    title: '重续通天之契',
    charCount: 48,
    chars: [
    { num: '203', char: '游', group: 'G5', existingCardId: null },
    { num: '204', char: '爬', group: 'G5', existingCardId: null },
    { num: '205', char: '看', group: 'G5', existingCardId: null },
    { num: '206', char: '听', group: 'G5', existingCardId: null },
    { num: '207', char: '说', group: 'G5', existingCardId: null },
    { num: '208', char: '读', group: 'G5', existingCardId: null },
    { num: '209', char: '写', group: 'G5', existingCardId: null },
    { num: '210', char: '念', group: 'G5', existingCardId: 'catalog-u5ff5' },
    { num: '211', char: '喊', group: 'G5', existingCardId: null },
    { num: '212', char: '叫', group: 'G5', existingCardId: null },
    { num: '213', char: '笑', group: 'G5', existingCardId: null },
    { num: '214', char: '哭', group: 'G5', existingCardId: 'catalog-u54ed' },
    { num: '215', char: '吃', group: 'G5', existingCardId: null },
    { num: '216', char: '喝', group: 'G5', existingCardId: null },
    { num: '217', char: '睡', group: 'G5', existingCardId: null },
    { num: '218', char: '洗', group: 'G5', existingCardId: 'catalog-u6d17' },
    { num: '219', char: '扫', group: 'G5', existingCardId: null },
    { num: '220', char: '擦', group: 'G5', existingCardId: null },
    { num: '221', char: '开', group: 'G5', existingCardId: null },
    { num: '222', char: '关', group: 'G5', existingCardId: null },
    { num: '223', char: '拿', group: 'G5', existingCardId: null },
    { num: '224', char: '放', group: 'G5', existingCardId: null },
    { num: '225', char: '来', group: 'G5', existingCardId: 'catalog-u6765' },
    { num: '226', char: '去', group: 'G5', existingCardId: 'catalog-u53bb' },
    { num: '227', char: '进', group: 'G5', existingCardId: 'catalog-u8fdb' },
    { num: '228', char: '出', group: 'G5', existingCardId: 'catalog-u51fa' },
    { num: '229', char: '回', group: 'G5', existingCardId: null },
    { num: '230', char: '到', group: 'G5', existingCardId: null },
    { num: '231', char: '往', group: 'G5', existingCardId: 'catalog-u5f80' },
    { num: '232', char: '登', group: 'G5', existingCardId: 'catalog-u767b' },
    { num: '233', char: '攀', group: 'G5', existingCardId: null },
    { num: '234', char: '爱', group: 'G5', existingCardId: null },
    { num: '235', char: '喜', group: 'G5', existingCardId: 'catalog-u559c' },
    { num: '236', char: '怒', group: 'G5', existingCardId: null },
    { num: '237', char: '悲', group: 'G5', existingCardId: null },
    { num: '238', char: '愁', group: 'G5', existingCardId: null },
    { num: '239', char: '思', group: 'G5', existingCardId: null },
    { num: '240', char: '想', group: 'G5', existingCardId: null },
    { num: '241', char: '知', group: 'G5', existingCardId: 'catalog-u77e5' },
    { num: '242', char: '懂', group: 'G5', existingCardId: null },
    { num: '243', char: '记', group: 'G5', existingCardId: null },
    { num: '244', char: '好', group: 'G5', existingCardId: 'catalog-u597d' },
    { num: '245', char: '坏', group: 'G5', existingCardId: null },
    { num: '246', char: '真', group: 'G5', existingCardId: 'catalog-u771f' },
    { num: '247', char: '假', group: 'G5', existingCardId: null },
    { num: '248', char: '新', group: 'G5', existingCardId: 'catalog-u65b0' },
    { num: '249', char: '旧', group: 'G5', existingCardId: 'catalog-u65e7' },
    { num: '250', char: '高', group: 'G5', existingCardId: 'catalog-u9ad8' }
    ],
  },
];

// 待补字：字表 300 字中游戏内尚无 cardId 的共 157 字（与字表文档「待补157」一致）。
export interface MissingChar { num: string; char: string; group: CharGroup; }
export const MISSING_CHARS: MissingChar[] = [
  { num: '024', char: '前', group: 'G1' },
  { num: '025', char: '后', group: 'G1' },
  { num: '026', char: '里', group: 'G1' },
  { num: '046', char: '江', group: 'G1' },
  { num: '048', char: '湖', group: 'G1' },
  { num: '049', char: '海', group: 'G1' },
  { num: '053', char: '爸', group: 'G2' },
  { num: '054', char: '妈', group: 'G2' },
  { num: '055', char: '爷', group: 'G2' },
  { num: '056', char: '奶', group: 'G2' },
  { num: '057', char: '哥', group: 'G2' },
  { num: '058', char: '姐', group: 'G2' },
  { num: '061', char: '孩', group: 'G2' },
  { num: '066', char: '你', group: 'G2' },
  { num: '068', char: '他', group: 'G2' },
  { num: '069', char: '她', group: 'G2' },
  { num: '071', char: '咱', group: 'G2' },
  { num: '072', char: '们', group: 'G2' },
  { num: '073', char: '谁', group: 'G2' },
  { num: '074', char: '这', group: 'G2' },
  { num: '075', char: '那', group: 'G2' },
  { num: '076', char: '哪', group: 'G2' },
  { num: '079', char: '昨', group: 'G2' },
  { num: '083', char: '冬', group: 'G2' },
  { num: '085', char: '晚', group: 'G2' },
  { num: '089', char: '时', group: 'G2' },
  { num: '096', char: '昼', group: 'G2' },
  { num: '101', char: '眼', group: 'G3' },
  { num: '105', char: '手', group: 'G3' },
  { num: '106', char: '足', group: 'G3' },
  { num: '111', char: '毛', group: 'G3' },
  { num: '113', char: '齿', group: 'G3' },
  { num: '116', char: '胸', group: 'G3' },
  { num: '117', char: '腰', group: 'G3' },
  { num: '118', char: '腿', group: 'G3' },
  { num: '119', char: '脚', group: 'G3' },
  { num: '120', char: '指', group: 'G3' },
  { num: '121', char: '掌', group: 'G3' },
  { num: '123', char: '汗', group: 'G3' },
  { num: '124', char: '泪', group: 'G3' },
  { num: '127', char: '音', group: 'G3' },
  { num: '128', char: '饭', group: 'G3' },
  { num: '130', char: '菜', group: 'G3' },
  { num: '131', char: '瓜', group: 'G3' },
  { num: '132', char: '果', group: 'G3' },
  { num: '133', char: '茶', group: 'G3' },
  { num: '136', char: '蛋', group: 'G3' },
  { num: '137', char: '油', group: 'G3' },
  { num: '138', char: '盐', group: 'G3' },
  { num: '139', char: '糖', group: 'G3' },
  { num: '140', char: '粥', group: 'G3' },
  { num: '141', char: '饼', group: 'G3' },
  { num: '142', char: '汤', group: 'G3' },
  { num: '144', char: '麦', group: 'G3' },
  { num: '145', char: '蔬', group: 'G3' },
  { num: '147', char: '房', group: 'G3' },
  { num: '148', char: '屋', group: 'G3' },
  { num: '150', char: '窗', group: 'G3' },
  { num: '152', char: '桌', group: 'G4' },
  { num: '153', char: '椅', group: 'G4' },
  { num: '154', char: '床', group: 'G4' },
  { num: '155', char: '灯', group: 'G4' },
  { num: '156', char: '楼', group: 'G4' },
  { num: '157', char: '契', group: 'G4' },
  { num: '158', char: '院', group: 'G4' },
  { num: '159', char: '巷', group: 'G4' },
  { num: '161', char: '路', group: 'G4' },
  { num: '162', char: '车', group: 'G4' },
  { num: '163', char: '船', group: 'G4' },
  { num: '165', char: '桥', group: 'G4' },
  { num: '167', char: '坡', group: 'G4' },
  { num: '169', char: '缸', group: 'G4' },
  { num: '171', char: '杯', group: 'G4' },
  { num: '172', char: '碗', group: 'G4' },
  { num: '173', char: '勺', group: 'G4' },
  { num: '174', char: '筷', group: 'G4' },
  { num: '176', char: '尺', group: 'G4' },
  { num: '177', char: '笔', group: 'G4' },
  { num: '178', char: '纸', group: 'G4' },
  { num: '179', char: '书', group: 'G4' },
  { num: '180', char: '本', group: 'G4' },
  { num: '181', char: '烬', group: 'G4' },
  { num: '183', char: '图', group: 'G4' },
  { num: '184', char: '册', group: 'G4' },
  { num: '185', char: '校', group: 'G4' },
  { num: '187', char: '师', group: 'G4' },
  { num: '189', char: '班', group: 'G4' },
  { num: '190', char: '课', group: 'G4' },
  { num: '192', char: '数', group: 'G4' },
  { num: '193', char: '语', group: 'G4' },
  { num: '194', char: '英', group: 'G4' },
  { num: '196', char: '跑', group: 'G4' },
  { num: '197', char: '跳', group: 'G4' },
  { num: '198', char: '站', group: 'G4' },
  { num: '200', char: '卧', group: 'G4' },
  { num: '202', char: '飞', group: 'G5' },
  { num: '203', char: '游', group: 'G5' },
  { num: '204', char: '爬', group: 'G5' },
  { num: '205', char: '看', group: 'G5' },
  { num: '206', char: '听', group: 'G5' },
  { num: '207', char: '说', group: 'G5' },
  { num: '208', char: '读', group: 'G5' },
  { num: '209', char: '写', group: 'G5' },
  { num: '211', char: '喊', group: 'G5' },
  { num: '212', char: '叫', group: 'G5' },
  { num: '213', char: '笑', group: 'G5' },
  { num: '215', char: '吃', group: 'G5' },
  { num: '216', char: '喝', group: 'G5' },
  { num: '217', char: '睡', group: 'G5' },
  { num: '219', char: '扫', group: 'G5' },
  { num: '220', char: '擦', group: 'G5' },
  { num: '221', char: '开', group: 'G5' },
  { num: '222', char: '关', group: 'G5' },
  { num: '223', char: '拿', group: 'G5' },
  { num: '224', char: '放', group: 'G5' },
  { num: '229', char: '回', group: 'G5' },
  { num: '230', char: '到', group: 'G5' },
  { num: '233', char: '攀', group: 'G5' },
  { num: '234', char: '爱', group: 'G5' },
  { num: '236', char: '怒', group: 'G5' },
  { num: '237', char: '悲', group: 'G5' },
  { num: '238', char: '愁', group: 'G5' },
  { num: '239', char: '思', group: 'G5' },
  { num: '240', char: '想', group: 'G5' },
  { num: '242', char: '懂', group: 'G5' },
  { num: '243', char: '记', group: 'G5' },
  { num: '245', char: '坏', group: 'G5' },
  { num: '247', char: '假', group: 'G5' },
  { num: '251', char: '低', group: 'G6' },
  { num: '253', char: '短', group: 'G6' },
  { num: '254', char: '宽', group: 'G6' },
  { num: '255', char: '窄', group: 'G6' },
  { num: '257', char: '薄', group: 'G6' },
  { num: '258', char: '轻', group: 'G6' },
  { num: '260', char: '快', group: 'G6' },
  { num: '261', char: '慢', group: 'G6' },
  { num: '262', char: '远', group: 'G6' },
  { num: '263', char: '近', group: 'G6' },
  { num: '264', char: '红', group: 'G6' },
  { num: '266', char: '蓝', group: 'G6' },
  { num: '269', char: '绿', group: 'G6' },
  { num: '270', char: '灰', group: 'G6' },
  { num: '271', char: '粉', group: 'G6' },
  { num: '272', char: '亮', group: 'G6' },
  { num: '273', char: '暗', group: 'G6' },
  { num: '275', char: '无', group: 'G6' },
  { num: '278', char: '会', group: 'G6' },
  { num: '279', char: '要', group: 'G6' },
  { num: '281', char: '应', group: 'G6' },
  { num: '282', char: '该', group: 'G6' },
  { num: '285', char: '功', group: 'G6' },
  { num: '287', char: '安', group: 'G6' },
  { num: '289', char: '平', group: 'G6' },
  { num: '292', char: '福', group: 'G6' },
  { num: '293', char: '忙', group: 'G6' },
  { num: '297', char: '禾', group: 'G6' },
  { num: '298', char: '兵', group: 'G6' },
  { num: '299', char: '祀', group: 'G6' },
  { num: '300', char: '婚', group: 'G6' },
];
// 拾遗字：原 300 字表中编号 251-300 的 50 字，移出主线剧情，作为探索「甲骨拾遗」投放池。
export interface SupplementChar { num: string; char: string; group: CharGroup; existingCardId: string | null; }
export const SUPPLEMENT_CHARS: SupplementChar[] = [
    { num: '251', char: '低', group: 'G6', existingCardId: null },
    { num: '252', char: '长', group: 'G6', existingCardId: 'catalog-u957f' },
    { num: '253', char: '短', group: 'G6', existingCardId: null },
    { num: '254', char: '宽', group: 'G6', existingCardId: null },
    { num: '255', char: '窄', group: 'G6', existingCardId: null },
    { num: '256', char: '厚', group: 'G6', existingCardId: 'catalog-u539a' },
    { num: '257', char: '薄', group: 'G6', existingCardId: null },
    { num: '258', char: '轻', group: 'G6', existingCardId: null },
    { num: '259', char: '重', group: 'G6', existingCardId: 'catalog-u91cd' },
    { num: '260', char: '快', group: 'G6', existingCardId: null },
    { num: '261', char: '慢', group: 'G6', existingCardId: null },
    { num: '262', char: '远', group: 'G6', existingCardId: null },
    { num: '263', char: '近', group: 'G6', existingCardId: null },
    { num: '264', char: '红', group: 'G6', existingCardId: null },
    { num: '265', char: '黄', group: 'G6', existingCardId: 'catalog-u9ec4' },
    { num: '266', char: '蓝', group: 'G6', existingCardId: null },
    { num: '267', char: '白', group: 'G6', existingCardId: 'catalog-u767d' },
    { num: '268', char: '黑', group: 'G6', existingCardId: 'catalog-u9ed1' },
    { num: '269', char: '绿', group: 'G6', existingCardId: null },
    { num: '270', char: '灰', group: 'G6', existingCardId: null },
    { num: '271', char: '粉', group: 'G6', existingCardId: null },
    { num: '272', char: '亮', group: 'G6', existingCardId: null },
    { num: '273', char: '暗', group: 'G6', existingCardId: null },
    { num: '274', char: '有', group: 'G6', existingCardId: 'catalog-u6709' },
    { num: '275', char: '无', group: 'G6', existingCardId: null },
    { num: '276', char: '能', group: 'G6', existingCardId: 'catalog-u80fd' },
    { num: '277', char: '可', group: 'G6', existingCardId: 'catalog-u53ef' },
    { num: '278', char: '会', group: 'G6', existingCardId: null },
    { num: '279', char: '要', group: 'G6', existingCardId: null },
    { num: '280', char: '得', group: 'G6', existingCardId: 'catalog-u5f97' },
    { num: '281', char: '应', group: 'G6', existingCardId: null },
    { num: '282', char: '该', group: 'G6', existingCardId: null },
    { num: '283', char: '敢', group: 'G6', existingCardId: 'catalog-u6562' },
    { num: '284', char: '力', group: 'G6', existingCardId: 'catalog-u529b' },
    { num: '285', char: '功', group: 'G6', existingCardId: null },
    { num: '286', char: '劳', group: 'G6', existingCardId: 'catalog-u52b3' },
    { num: '287', char: '安', group: 'G6', existingCardId: null },
    { num: '288', char: '危', group: 'G6', existingCardId: 'catalog-u5371' },
    { num: '289', char: '平', group: 'G6', existingCardId: null },
    { num: '290', char: '顺', group: 'G6', existingCardId: 'catalog-u987a' },
    { num: '291', char: '利', group: 'G6', existingCardId: 'catalog-u5229' },
    { num: '292', char: '福', group: 'G6', existingCardId: null },
    { num: '293', char: '忙', group: 'G6', existingCardId: null },
    { num: '294', char: '基', group: 'G6', existingCardId: 'catalog-u57fa' },
    { num: '295', char: '每', group: 'G6', existingCardId: 'catalog-u6bcf' },
    { num: '296', char: '用', group: 'G6', existingCardId: 'catalog-u7528' },
    { num: '297', char: '禾', group: 'G6', existingCardId: null },
    { num: '298', char: '兵', group: 'G6', existingCardId: null },
    { num: '299', char: '祀', group: 'G6', existingCardId: null },
    { num: '300', char: '婚', group: 'G6', existingCardId: null }
];


// 字量校验：主线 5+12+19+26+26+32+38+44+48 = 250；拾遗固定 50，完整图鉴共 300。
export const CHAR_PLAN_TOTAL = CHAPTER_CHAR_PLANS.reduce((s, c) => s + c.charCount, 0);
export const SUPPLEMENT_CHAR_TOTAL = SUPPLEMENT_CHARS.length;
export const FULL_CATALOG_TOTAL = CHAR_PLAN_TOTAL + SUPPLEMENT_CHAR_TOTAL;

// 模块加载时执行数据完整性校验，错误数据直接阻止启动，避免章节进行到中途才暴露卡死问题。
(() => {
  const mainChars = CHAPTER_CHAR_PLANS.reduce<PlannedChar[]>((all, plan) => all.concat(plan.chars), []);
  const allChars = mainChars.concat(SUPPLEMENT_CHARS);
  const duplicateValues = (values: string[]) => values.filter((value, index) => values.indexOf(value) !== index);
  const duplicateChapterIds = duplicateValues(CHAPTER_CHAR_PLANS.map(plan => plan.chapterId));
  const duplicateChars = duplicateValues(allChars.map(item => item.char));
  const duplicateNums = duplicateValues(allChars.map(item => item.num));
  const badChapterCounts = CHAPTER_CHAR_PLANS.filter(plan => plan.charCount !== plan.chars.length);

  if (CHAR_PLAN_TOTAL !== 250 || mainChars.length !== 250) {
    throw new Error(`[ChapterCharMap] 主线字数异常：声明 ${CHAR_PLAN_TOTAL}，实际 ${mainChars.length}，应为 250。`);
  }
  if (SUPPLEMENT_CHAR_TOTAL !== 50 || FULL_CATALOG_TOTAL !== 300) {
    throw new Error(`[ChapterCharMap] 拾遗/图鉴字数异常：拾遗 ${SUPPLEMENT_CHAR_TOTAL}，总计 ${FULL_CATALOG_TOTAL}。`);
  }
  if (badChapterCounts.length > 0) {
    throw new Error(`[ChapterCharMap] 章节声明字数与实际数组不一致：${badChapterCounts.map(plan => plan.chapterId).join(', ')}。`);
  }
  if (duplicateChapterIds.length > 0 || duplicateChars.length > 0 || duplicateNums.length > 0) {
    throw new Error(
      `[ChapterCharMap] 数据重复：章节 ${[...new Set(duplicateChapterIds)].join(', ') || '无'}；`
      + `文字 ${[...new Set(duplicateChars)].join(', ') || '无'}；编号 ${[...new Set(duplicateNums)].join(', ') || '无'}。`,
    );
  }
})();
