import { StoryChapterDefinition } from './StoryTypes';

// 第五章：护送归途
// 护送随行·行进式占卜（NPC 跟随玩家，需 YinXuCity 支持 follower 型常驻节点）
// 字量 26，全部来自 ChapterCharMap 第 5 章分配（编号 063~088）。
export const CHAPTER_FIVE_ID = 'chapter-5-escort-home';
// 归人·阿归 站位（坐标待 Cocos 微调）；进章传送落其旁。

export const CHAPTER_FIVE_FRAGMENT_CARDS = [
  { seekStepId: 'chapter-5-escort-home-seek-001', lessonStepId: 'chapter-5-escort-home-lesson-001', cardId: 'catalog-u5973', character: '女' },
  { seekStepId: 'chapter-5-escort-home-seek-002', lessonStepId: 'chapter-5-escort-home-lesson-002', cardId: 'catalog-u8001', character: '老' },
  { seekStepId: 'chapter-5-escort-home-seek-003', lessonStepId: 'chapter-5-escort-home-lesson-003', cardId: 'catalog-u7537', character: '男' },
  { seekStepId: 'chapter-5-escort-home-seek-004', lessonStepId: 'chapter-5-escort-home-lesson-004', cardId: 'catalog-u4f60', character: '你' },
  { seekStepId: 'chapter-5-escort-home-seek-005', lessonStepId: 'chapter-5-escort-home-lesson-005', cardId: 'catalog-u6211', character: '我' },
  { seekStepId: 'chapter-5-escort-home-seek-006', lessonStepId: 'chapter-5-escort-home-lesson-006', cardId: 'catalog-u4ed6', character: '他' },
  { seekStepId: 'chapter-5-escort-home-seek-007', lessonStepId: 'chapter-5-escort-home-lesson-007', cardId: 'catalog-u5979', character: '她' },
  { seekStepId: 'chapter-5-escort-home-seek-008', lessonStepId: 'chapter-5-escort-home-lesson-008', cardId: 'catalog-u5b83', character: '它' },
  { seekStepId: 'chapter-5-escort-home-seek-009', lessonStepId: 'chapter-5-escort-home-lesson-009', cardId: 'catalog-u54b1', character: '咱' },
  { seekStepId: 'chapter-5-escort-home-seek-010', lessonStepId: 'chapter-5-escort-home-lesson-010', cardId: 'catalog-u4eec', character: '们' },
  { seekStepId: 'chapter-5-escort-home-seek-011', lessonStepId: 'chapter-5-escort-home-lesson-011', cardId: 'catalog-u8c01', character: '谁' },
  { seekStepId: 'chapter-5-escort-home-seek-012', lessonStepId: 'chapter-5-escort-home-lesson-012', cardId: 'catalog-u8fd9', character: '这' },
  { seekStepId: 'chapter-5-escort-home-seek-013', lessonStepId: 'chapter-5-escort-home-lesson-013', cardId: 'catalog-u90a3', character: '那' },
  { seekStepId: 'chapter-5-escort-home-seek-014', lessonStepId: 'chapter-5-escort-home-lesson-014', cardId: 'catalog-u54ea', character: '哪' },
  { seekStepId: 'chapter-5-escort-home-seek-015', lessonStepId: 'chapter-5-escort-home-lesson-015', cardId: 'catalog-u4eca', character: '今' },
  { seekStepId: 'chapter-5-escort-home-seek-016', lessonStepId: 'chapter-5-escort-home-lesson-016', cardId: 'catalog-u660e', character: '明' },
  { seekStepId: 'chapter-5-escort-home-seek-017', lessonStepId: 'chapter-5-escort-home-lesson-017', cardId: 'catalog-u6628', character: '昨' },
  { seekStepId: 'chapter-5-escort-home-seek-018', lessonStepId: 'chapter-5-escort-home-lesson-018', cardId: 'catalog-u6625', character: '春' },
  { seekStepId: 'chapter-5-escort-home-seek-019', lessonStepId: 'chapter-5-escort-home-lesson-019', cardId: 'catalog-u590f', character: '夏' },
  { seekStepId: 'chapter-5-escort-home-seek-020', lessonStepId: 'chapter-5-escort-home-lesson-020', cardId: 'catalog-u79cb', character: '秋' },
  { seekStepId: 'chapter-5-escort-home-seek-021', lessonStepId: 'chapter-5-escort-home-lesson-021', cardId: 'catalog-u51ac', character: '冬' },
  { seekStepId: 'chapter-5-escort-home-seek-022', lessonStepId: 'chapter-5-escort-home-lesson-022', cardId: 'catalog-u65e9', character: '早' },
  { seekStepId: 'chapter-5-escort-home-seek-023', lessonStepId: 'chapter-5-escort-home-lesson-023', cardId: 'catalog-u665a', character: '晚' },
  { seekStepId: 'chapter-5-escort-home-seek-024', lessonStepId: 'chapter-5-escort-home-lesson-024', cardId: 'catalog-u5348', character: '午' },
  { seekStepId: 'chapter-5-escort-home-seek-025', lessonStepId: 'chapter-5-escort-home-lesson-025', cardId: 'catalog-u6668', character: '晨' },
  { seekStepId: 'chapter-5-escort-home-seek-026', lessonStepId: 'chapter-5-escort-home-lesson-026', cardId: 'catalog-u660f', character: '昏' },
] as const;

export const chapterFiveDefinition: StoryChapterDefinition = {
  id: CHAPTER_FIVE_ID,
  title: '第五章：护送归途',
  firstStepId: 'chapter-5-escort-home-opening',
  steps: [
    {
      id: 'chapter-5-escort-home-opening',
      chapterId: CHAPTER_FIVE_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '上一程山林的裂纹越出林线，指向山外一条车马喧阗的护送道。你循兆而行，遇上正要护送祭器归乡、却屡屡在途中受阻的归人·阿归。' },
        { speaker: '贞人师', text: '这一程不在宗庙，而在道上、桥畔、驿站之间。归人·阿归守着一桩要紧的事，需你以甲骨一一卜算。' },
        { speaker: '归人·阿归', text: '守卜人，我名阿归。此去事繁，你若相助，便以你卜出的甲骨引我趋吉辨伪——如何？' },
        { speaker: '提示', kind: 'system', text: '第五章：护送归途开启。当前目标：寻到归人·阿归，在这一程各处寻回失语的行旅护送甲骨碎片。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-5-escort-home-reach-npc',
      checkpoint: true,
    },
    {
      id: 'chapter-5-escort-home-reach-npc',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 启程', detail: '走到归人·阿归身边，听他（她）讲清这一程要卜的事。', storyLocationId: 'chapter-5-fields-npc', targetRadius: 200 },
      completeOn: 'npc-reached',
      nextStepId: 'chapter-5-escort-home-npc-dialogue',
    },
    {
      id: 'chapter-5-escort-home-npc-dialogue',
      chapterId: CHAPTER_FIVE_ID,
      dialogue: [
        { speaker: '归人·阿归', text: '我这一程要办的，是「行旅护送」。这一带散着26枚记着这事的老刻，自打天意断了就再没响过。' },
        { speaker: '你', text: '我不是来指路，是来听骨。你若信我，便一枚枚唤醒它们，兆纹自会引我们看清明细。' },
        { speaker: '归人·阿归', text: '那便随我来。沿途的碎甲你且一枚枚挖出、认明——「女老男你、你我他她、今明春夏秋冬、早午晚晨昏」这些，都在这一程里。' },
        { speaker: '提示', kind: 'system', text: '任务更新：在第五章：护送归途中挖掘并发掘失语的甲骨碎片。每寻回一枚，阿归便信你一分。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-5-escort-home-seek-001',
      checkpoint: true,
    },
    {
      id: 'chapter-5-escort-home-seek-001',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '岔道旁的土层里沉着微光。挖出「女」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-001',
    },
    {
      id: 'chapter-5-escort-home-lesson-001',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识女字', detail: '观察骨纹，认出这是「女」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-002',
    },
    {
      id: 'chapter-5-escort-home-seek-002',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '驿站残垣的土层里沉着微光。挖出「老」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-002',
    },
    {
      id: 'chapter-5-escort-home-lesson-002',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识老字', detail: '观察骨纹，认出这是「老」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-003',
    },
    {
      id: 'chapter-5-escort-home-seek-003',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '车辙尽头的土层里沉着微光。挖出「男」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-003',
    },
    {
      id: 'chapter-5-escort-home-lesson-003',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识男字', detail: '观察骨纹，认出这是「男」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-004',
    },
    {
      id: 'chapter-5-escort-home-seek-004',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '桥畔柳下的土层里沉着微光。挖出「你」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-004',
    },
    {
      id: 'chapter-5-escort-home-lesson-004',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识你字', detail: '观察骨纹，认出这是「你」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-005',
    },
    {
      id: 'chapter-5-escort-home-seek-005',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '林梢风口的土层里沉着微光。挖出「我」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-005',
    },
    {
      id: 'chapter-5-escort-home-lesson-005',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识我字', detail: '观察骨纹，认出这是「我」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-006',
    },
    {
      id: 'chapter-5-escort-home-seek-006',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '营火余烬的土层里沉着微光。挖出「他」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-006',
    },
    {
      id: 'chapter-5-escort-home-lesson-006',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识他字', detail: '观察骨纹，认出这是「他」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-007',
    },
    {
      id: 'chapter-5-escort-home-seek-007',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '田垄分界的土层里沉着微光。挖出「她」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-007',
    },
    {
      id: 'chapter-5-escort-home-lesson-007',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识她字', detail: '观察骨纹，认出这是「她」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-008',
    },
    {
      id: 'chapter-5-escort-home-seek-008',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '溪桥转角的土层里沉着微光。挖出「它」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-008',
    },
    {
      id: 'chapter-5-escort-home-lesson-008',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识它字', detail: '观察骨纹，认出这是「它」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-009',
    },
    {
      id: 'chapter-5-escort-home-seek-009',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '古驿道边的土层里沉着微光。挖出「咱」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-009',
    },
    {
      id: 'chapter-5-escort-home-lesson-009',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识咱字', detail: '观察骨纹，认出这是「咱」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-010',
    },
    {
      id: 'chapter-5-escort-home-seek-010',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '歇脚石上的土层里沉着微光。挖出「们」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-010',
    },
    {
      id: 'chapter-5-escort-home-lesson-010',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识们字', detail: '观察骨纹，认出这是「们」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-011',
    },
    {
      id: 'chapter-5-escort-home-seek-011',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '暮野孤灯的土层里沉着微光。挖出「谁」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-011',
    },
    {
      id: 'chapter-5-escort-home-lesson-011',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识谁字', detail: '观察骨纹，认出这是「谁」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-012',
    },
    {
      id: 'chapter-5-escort-home-seek-012',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '归途岔口的土层里沉着微光。挖出「这」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-012',
    },
    {
      id: 'chapter-5-escort-home-lesson-012',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识这字', detail: '观察骨纹，认出这是「这」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-013',
    },
    {
      id: 'chapter-5-escort-home-seek-013',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '车马歇处的土层里沉着微光。挖出「那」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-013',
    },
    {
      id: 'chapter-5-escort-home-lesson-013',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识那字', detail: '观察骨纹，认出这是「那」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-midstream',
    },
    {
      id: 'chapter-5-escort-home-midstream',
      chapterId: CHAPTER_FIVE_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '半数碎甲归位的刹那，阿归一直绷着的神色松了下来。这一程的脉络，第一次在你们之间连成线。' },
        { speaker: '归人·阿归', text: '原以为这桩「行旅护送」只是我一家的事。可你挖出的骨片，真的一枚枚在我眼前活了——这回我信你。' },
        { speaker: '神秘低语', text: '……骨归其序，事乃成章……' },
        { speaker: '贞人师', text: '中段已过，阿归终肯托付。继续寻回余下的碎甲，这一程的真相便近了。' },
        { speaker: '提示', kind: 'system', text: '中段：13字已聚，阿归托付于你。继续入深处，寻回余下碎甲。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-5-escort-home-seek-014',
      checkpoint: true,
    },
    {
      id: 'chapter-5-escort-home-seek-014',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '远郊野径的土层里沉着微光。挖出「哪」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-014',
    },
    {
      id: 'chapter-5-escort-home-lesson-014',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识哪字', detail: '观察骨纹，认出这是「哪」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-015',
    },
    {
      id: 'chapter-5-escort-home-seek-015',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '岔道旁的土层里沉着微光。挖出「今」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-015',
    },
    {
      id: 'chapter-5-escort-home-lesson-015',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识今字', detail: '观察骨纹，认出这是「今」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-016',
    },
    {
      id: 'chapter-5-escort-home-seek-016',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '驿站残垣的土层里沉着微光。挖出「明」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-016',
    },
    {
      id: 'chapter-5-escort-home-lesson-016',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识明字', detail: '观察骨纹，认出这是「明」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-017',
    },
    {
      id: 'chapter-5-escort-home-seek-017',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '车辙尽头的土层里沉着微光。挖出「昨」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-017',
    },
    {
      id: 'chapter-5-escort-home-lesson-017',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识昨字', detail: '观察骨纹，认出这是「昨」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-018',
    },
    {
      id: 'chapter-5-escort-home-seek-018',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '桥畔柳下的土层里沉着微光。挖出「春」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-018',
    },
    {
      id: 'chapter-5-escort-home-lesson-018',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识春字', detail: '观察骨纹，认出这是「春」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-019',
    },
    {
      id: 'chapter-5-escort-home-seek-019',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '林梢风口的土层里沉着微光。挖出「夏」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-019',
    },
    {
      id: 'chapter-5-escort-home-lesson-019',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识夏字', detail: '观察骨纹，认出这是「夏」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-020',
    },
    {
      id: 'chapter-5-escort-home-seek-020',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '营火余烬的土层里沉着微光。挖出「秋」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-020',
    },
    {
      id: 'chapter-5-escort-home-lesson-020',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识秋字', detail: '观察骨纹，认出这是「秋」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-021',
    },
    {
      id: 'chapter-5-escort-home-seek-021',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '田垄分界的土层里沉着微光。挖出「冬」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-021',
    },
    {
      id: 'chapter-5-escort-home-lesson-021',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识冬字', detail: '观察骨纹，认出这是「冬」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-022',
    },
    {
      id: 'chapter-5-escort-home-seek-022',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '溪桥转角的土层里沉着微光。挖出「早」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-022',
    },
    {
      id: 'chapter-5-escort-home-lesson-022',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识早字', detail: '观察骨纹，认出这是「早」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-023',
    },
    {
      id: 'chapter-5-escort-home-seek-023',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '古驿道边的土层里沉着微光。挖出「晚」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-023',
    },
    {
      id: 'chapter-5-escort-home-lesson-023',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识晚字', detail: '观察骨纹，认出这是「晚」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-024',
    },
    {
      id: 'chapter-5-escort-home-seek-024',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '歇脚石上的土层里沉着微光。挖出「午」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-024',
    },
    {
      id: 'chapter-5-escort-home-lesson-024',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识午字', detail: '观察骨纹，认出这是「午」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-025',
    },
    {
      id: 'chapter-5-escort-home-seek-025',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '暮野孤灯的土层里沉着微光。挖出「晨」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-025',
    },
    {
      id: 'chapter-5-escort-home-lesson-025',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识晨字', detail: '观察骨纹，认出这是「晨」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-seek-026',
    },
    {
      id: 'chapter-5-escort-home-seek-026',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 寻骨', detail: '归途岔口的土层里沉着微光。挖出「昏」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-5-escort-home-lesson-026',
    },
    {
      id: 'chapter-5-escort-home-lesson-026',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 辨识昏字', detail: '观察骨纹，认出这是「昏」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-5-escort-home-fragment-awakens',
    },
    {
      id: 'chapter-5-escort-home-fragment-awakens',
      chapterId: CHAPTER_FIVE_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '26枚行旅护送碎甲在掌心排开。你按这一程的脉络理好，骨纹竟投出一道微光，照见阿归要办之事的去向。' },
        { speaker: '神秘低语', text: '……行旅护送毕，骨已成章……' },
        { speaker: '你', text: '原来这一程记下的不是死物，是「女老男你、你我他她、今明春夏秋冬、早午晚晨昏」里活着的学问。它们齐了，去路才显在眼前。' },
        { speaker: '归人·阿归', text: '我听不见金光里的声音，可骨片真的在你手里连成了路！守卜人，你果然是贞人师说的那个人。' },
        { speaker: '提示', kind: 'system', text: '获得：「女老男你、你我他她、今明春夏秋冬、早午晚晨昏」26枚行旅护送甲骨碎片。卜力已苏醒，可落为天意之辞。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-5-escort-home-first-request',
    },
    {
      id: 'chapter-5-escort-home-first-request',
      chapterId: CHAPTER_FIVE_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '26枚碎甲归位，阿归这一桩「行旅护送」的脉络已清。可尚有未解的悬疑，要借卜力一问。' },
        { speaker: '归人·阿归', text: '守卜人，这26枚甲骨记下的事，我已信了八九分。可还有三桩悬案，能用这些字卜一卜么？' },
        { speaker: '你', text: '（你斟酌：三问牵连，当一卜接一卜地解。取过一枚甲骨——先卜其一，其余的，且待兆纹引你去看。）' },
        { speaker: '贞人师', text: '去吧。以这一程的卜力，为阿归卜算「归途安危、途中吉时、接应之人」三桩悬案。每解一桩，卜力便积一分。' },
        { speaker: '提示', kind: 'system', text: '守卜任务开启（第一轮）：为归人·阿归卜算「归途安危」，留意兆纹里多出的那道裂纹。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-5-escort-home-enter-temple',
      checkpoint: true,
    },
    {
      id: 'chapter-5-escort-home-enter-temple',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第五章：护送归途 · 问卜', detail: '随归人·阿归返回宗庙内殿，准备以本章甲骨问卜。', storyLocationId: 'city-divination-temple', targetRadius: 110 },
      completeOn: 'temple-entered',
      nextStepId: 'chapter-5-escort-home-take-seat',
    },
    {
      id: 'chapter-5-escort-home-take-seat',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '问卜 · 入席', detail: '走到内殿占卜席前，点击“坐下”，听归人·阿归讲清要卜之事。' },
      completeOn: 'temple-seat-reached',
      nextStepId: 'chapter-5-escort-home-divination-1',
    },
    {
      id: 'chapter-5-escort-home-divination-1',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第1轮问卜 · 归途安危', detail: '归人·阿归请你以本章甲骨卜算「归途安危」。' },
      completeOn: 'divination-completed',
      nextStepId: 'chapter-5-escort-home-divination-2',
      checkpoint: true,
    },
    {
      id: 'chapter-5-escort-home-divination-2',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第2轮问卜 · 途中吉时', detail: '归人·阿归请你以本章甲骨卜算「途中吉时」。' },
      completeOn: 'divination-completed',
      nextStepId: 'chapter-5-escort-home-divination-3',
      checkpoint: true,
    },
    {
      id: 'chapter-5-escort-home-divination-3',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '第3轮问卜 · 接应之人', detail: '归人·阿归请你以本章甲骨卜算「接应之人」。' },
      completeOn: 'divination-completed',
      nextStepId: 'chapter-5-escort-home-leave-seat',
    },
    {
      id: 'chapter-5-escort-home-leave-seat',
      chapterId: CHAPTER_FIVE_ID,
      objective: { title: '异常兆纹', detail: '完成三轮占卜后起身，查看甲骨额外显出的那道裂纹。' },
      completeOn: 'result-confirmed',
      nextStepId: 'chapter-5-escort-home-clue-revealed',
    },
    {
      id: 'chapter-5-escort-home-clue-revealed',
      chapterId: CHAPTER_FIVE_ID,
      dialogue: [
        { speaker: '归人·阿归', text: '原来「归途安危、途中吉时、接应之人」三问，兆纹都指向下一处——兆纹越过护送道，拐进一片荒废的宗庙——古墟残灯，正等你去点亮。' },
        { speaker: '旁白', kind: 'narration', text: '三卜既毕，兆纹并未熄灭。几道裂纹缓缓延伸，竟越过这一程，指向「古墟残灯」。' },
        { speaker: '神秘低语', text: '……古墟残灯……有骨……待人相续……' },
        { speaker: '贞人师', text: '三轮卜辞彼此牵引，这道裂纹拐出了这一程——下一处碎甲，在「古墟残灯」里。' },
        { speaker: '提示', kind: 'system', text: '第五章：护送归途完成。获得线索「古墟残灯」，下一章已开启。' },
      ],
      completeOn: 'dialogue-completed',
      checkpoint: true,
    },
  ],
};
