import { StoryChapterDefinition } from './StoryTypes';

// 第七章：错册余火
// 文献辨伪·限时抢救（火蔓延紧张感，偏智力多选辨伪）
// 字量 38，全部来自 ChapterCharMap 第 7 章分配（编号 121~158）。
export const CHAPTER_SEVEN_ID = 'chapter-7-wrong-scroll';
// 守册·阿简 站位（坐标待 Cocos 微调）；进章传送落其旁。

export const CHAPTER_SEVEN_FRAGMENT_CARDS = [
  { seekStepId: 'chapter-7-wrong-scroll-seek-001', lessonStepId: 'chapter-7-wrong-scroll-lesson-001', cardId: 'catalog-u638c', character: '掌' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-002', lessonStepId: 'chapter-7-wrong-scroll-lesson-002', cardId: 'catalog-u8840', character: '血' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-003', lessonStepId: 'chapter-7-wrong-scroll-lesson-003', cardId: 'catalog-u6c57', character: '汗' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-004', lessonStepId: 'chapter-7-wrong-scroll-lesson-004', cardId: 'catalog-u6cea', character: '泪' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-005', lessonStepId: 'chapter-7-wrong-scroll-lesson-005', cardId: 'catalog-u6c14', character: '气' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-006', lessonStepId: 'chapter-7-wrong-scroll-lesson-006', cardId: 'catalog-u58f0', character: '声' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-007', lessonStepId: 'chapter-7-wrong-scroll-lesson-007', cardId: 'catalog-u97f3', character: '音' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-008', lessonStepId: 'chapter-7-wrong-scroll-lesson-008', cardId: 'catalog-u996d', character: '饭' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-009', lessonStepId: 'chapter-7-wrong-scroll-lesson-009', cardId: 'catalog-u7c73', character: '米' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-010', lessonStepId: 'chapter-7-wrong-scroll-lesson-010', cardId: 'catalog-u83dc', character: '菜' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-011', lessonStepId: 'chapter-7-wrong-scroll-lesson-011', cardId: 'catalog-u74dc', character: '瓜' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-012', lessonStepId: 'chapter-7-wrong-scroll-lesson-012', cardId: 'catalog-u679c', character: '果' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-013', lessonStepId: 'chapter-7-wrong-scroll-lesson-013', cardId: 'catalog-u8336', character: '茶' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-014', lessonStepId: 'chapter-7-wrong-scroll-lesson-014', cardId: 'catalog-u9152', character: '酒' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-015', lessonStepId: 'chapter-7-wrong-scroll-lesson-015', cardId: 'catalog-u8089', character: '肉' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-016', lessonStepId: 'chapter-7-wrong-scroll-lesson-016', cardId: 'catalog-u86cb', character: '蛋' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-017', lessonStepId: 'chapter-7-wrong-scroll-lesson-017', cardId: 'catalog-u6cb9', character: '油' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-018', lessonStepId: 'chapter-7-wrong-scroll-lesson-018', cardId: 'catalog-u76d0', character: '盐' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-019', lessonStepId: 'chapter-7-wrong-scroll-lesson-019', cardId: 'catalog-u7cd6', character: '糖' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-020', lessonStepId: 'chapter-7-wrong-scroll-lesson-020', cardId: 'catalog-u7ca5', character: '粥' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-021', lessonStepId: 'chapter-7-wrong-scroll-lesson-021', cardId: 'catalog-u997c', character: '饼' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-022', lessonStepId: 'chapter-7-wrong-scroll-lesson-022', cardId: 'catalog-u6c64', character: '汤' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-023', lessonStepId: 'chapter-7-wrong-scroll-lesson-023', cardId: 'catalog-u5b57', character: '字' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-024', lessonStepId: 'chapter-7-wrong-scroll-lesson-024', cardId: 'catalog-u9ea6', character: '麦' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-025', lessonStepId: 'chapter-7-wrong-scroll-lesson-025', cardId: 'catalog-u852c', character: '蔬' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-026', lessonStepId: 'chapter-7-wrong-scroll-lesson-026', cardId: 'catalog-u5bb6', character: '家' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-027', lessonStepId: 'chapter-7-wrong-scroll-lesson-027', cardId: 'catalog-u623f', character: '房' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-028', lessonStepId: 'chapter-7-wrong-scroll-lesson-028', cardId: 'catalog-u5c4b', character: '屋' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-029', lessonStepId: 'chapter-7-wrong-scroll-lesson-029', cardId: 'catalog-u95e8', character: '门' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-030', lessonStepId: 'chapter-7-wrong-scroll-lesson-030', cardId: 'catalog-u7a97', character: '窗' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-031', lessonStepId: 'chapter-7-wrong-scroll-lesson-031', cardId: 'catalog-u5899', character: '墙' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-032', lessonStepId: 'chapter-7-wrong-scroll-lesson-032', cardId: 'catalog-u684c', character: '桌' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-033', lessonStepId: 'chapter-7-wrong-scroll-lesson-033', cardId: 'catalog-u6905', character: '椅' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-034', lessonStepId: 'chapter-7-wrong-scroll-lesson-034', cardId: 'catalog-u5e8a', character: '床' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-035', lessonStepId: 'chapter-7-wrong-scroll-lesson-035', cardId: 'catalog-u706f', character: '灯' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-036', lessonStepId: 'chapter-7-wrong-scroll-lesson-036', cardId: 'catalog-u697c', character: '楼' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-037', lessonStepId: 'chapter-7-wrong-scroll-lesson-037', cardId: 'catalog-u5951', character: '契' },
  { seekStepId: 'chapter-7-wrong-scroll-seek-038', lessonStepId: 'chapter-7-wrong-scroll-lesson-038', cardId: 'catalog-u9662', character: '院' },
] as const;

export const chapterSevenDefinition: StoryChapterDefinition = {
  id: CHAPTER_SEVEN_ID,
  title: '第七章：错册余火',
  firstStepId: 'chapter-7-wrong-scroll-opening',
  steps: [
    {
      id: 'chapter-7-wrong-scroll-opening',
      chapterId: CHAPTER_SEVEN_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '残灯次第亮起，照见废墟深处一间将焚的书库——竹简卷帙在余火里蜷曲发焦。守着典册、却被真伪难辨的错简困住的守册·阿简，正焦灼地等你相助。' },
        { speaker: '贞人师', text: '这一程在火边、书堆里、错简之间。守册·阿简守着一桩要紧的事，需你以甲骨一一卜算。' },
        { speaker: '守册·阿简', text: '守卜人，我名阿简。此去事繁，你若相助，便以你卜出的甲骨引我趋吉辨伪——如何？' },
        { speaker: '提示', kind: 'system', text: '第七章：错册余火开启。当前目标：寻到守册·阿简，在这一程各处寻回失语的文献辨伪甲骨碎片。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-7-wrong-scroll-reach-npc',
      checkpoint: true,
    },
    {
      id: 'chapter-7-wrong-scroll-reach-npc',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 启程', detail: '走到守册·阿简身边，听他（她）讲清这一程要卜的事。', storyLocationId: 'chapter-7-highland-npc', targetRadius: 200 },
      completeOn: 'npc-reached',
      nextStepId: 'chapter-7-wrong-scroll-npc-dialogue',
    },
    {
      id: 'chapter-7-wrong-scroll-npc-dialogue',
      chapterId: CHAPTER_SEVEN_ID,
      dialogue: [
        { speaker: '守册·阿简', text: '我这一程要办的，是「文献辨伪」。这一带散着38枚记着这事的老刻，自打天意断了就再没响过。' },
        { speaker: '你', text: '我不是来指路，是来听骨。你若信我，便一枚枚唤醒它们，兆纹自会引我们看清明细。' },
        { speaker: '守册·阿简', text: '那便随我来。沿途的碎甲你且一枚枚挖出、认明——「掌血汗泪、气声音乐、米菜瓜果茶酒肉蛋油盐糖粥饼汤、字麦蔬家房屋门窗户墙桌椅床灯楼契院」这些，都在这一程里。' },
        { speaker: '提示', kind: 'system', text: '任务更新：在第七章：错册余火中挖掘并发掘失语的甲骨碎片。每寻回一枚，阿简便信你一分。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-001',
      checkpoint: true,
    },
    {
      id: 'chapter-7-wrong-scroll-seek-001',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '将焚书堆的土层里沉着微光。挖出「掌」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-001',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-001',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识掌字', detail: '观察骨纹，认出这是「掌」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-002',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-002',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '余火边缘的土层里沉着微光。挖出「血」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-002',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-002',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识血字', detail: '观察骨纹，认出这是「血」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-003',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-003',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '错简交叠的土层里沉着微光。挖出「汗」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-003',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-003',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识汗字', detail: '观察骨纹，认出这是「汗」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-004',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-004',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '墨迹漫漶的土层里沉着微光。挖出「泪」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-004',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-004',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识泪字', detail: '观察骨纹，认出这是「泪」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-005',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-005',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '残卷夹层的土层里沉着微光。挖出「气」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-005',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-005',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识气字', detail: '观察骨纹，认出这是「气」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-006',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-006',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '焦黄书页的土层里沉着微光。挖出「声」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-006',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-006',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识声字', detail: '观察骨纹，认出这是「声」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-007',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-007',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '竹简散落的土层里沉着微光。挖出「音」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-007',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-007',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识音字', detail: '观察骨纹，认出这是「音」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-008',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-008',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '案几倒塌的土层里沉着微光。挖出「饭」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-008',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-008',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识饭字', detail: '观察骨纹，认出这是「饭」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-009',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-009',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '烟火呛处的土层里沉着微光。挖出「米」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-009',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-009',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识米字', detail: '观察骨纹，认出这是「米」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-010',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-010',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '字纸残角的土层里沉着微光。挖出「菜」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-010',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-010',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识菜字', detail: '观察骨纹，认出这是「菜」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-011',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-011',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '库房暗格的土层里沉着微光。挖出「瓜」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-011',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-011',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识瓜字', detail: '观察骨纹，认出这是「瓜」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-012',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-012',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '油灯将尽的土层里沉着微光。挖出「果」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-012',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-012',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识果字', detail: '观察骨纹，认出这是「果」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-013',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-013',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '抢运通道的土层里沉着微光。挖出「茶」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-013',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-013',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识茶字', detail: '观察骨纹，认出这是「茶」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-014',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-014',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '灰烬微光的土层里沉着微光。挖出「酒」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-014',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-014',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识酒字', detail: '观察骨纹，认出这是「酒」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-015',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-015',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '断编裂简的土层里沉着微光。挖出「肉」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-015',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-015',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识肉字', detail: '观察骨纹，认出这是「肉」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-016',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-016',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '焚风掠过的土层里沉着微光。挖出「蛋」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-016',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-016',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识蛋字', detail: '观察骨纹，认出这是「蛋」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-017',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-017',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '残字浮起的土层里沉着微光。挖出「油」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-017',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-017',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识油字', detail: '观察骨纹，认出这是「油」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-018',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-018',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '抢救台前的土层里沉着微光。挖出「盐」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-018',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-018',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识盐字', detail: '观察骨纹，认出这是「盐」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-019',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-019',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '湿布覆处的土层里沉着微光。挖出「糖」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-019',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-019',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识糖字', detail: '观察骨纹，认出这是「糖」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-midstream',
    },
    {
      id: 'chapter-7-wrong-scroll-midstream',
      chapterId: CHAPTER_SEVEN_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '半数碎甲归位的刹那，阿简一直绷着的神色松了下来。这一程的脉络，第一次在你们之间连成线。' },
        { speaker: '守册·阿简', text: '原以为这桩「文献辨伪」只是我一家的事。可你挖出的骨片，真的一枚枚在我眼前活了——这回我信你。' },
        { speaker: '神秘低语', text: '……骨归其序，事乃成章……' },
        { speaker: '贞人师', text: '中段已过，阿简终肯托付。继续寻回余下的碎甲，这一程的真相便近了。' },
        { speaker: '提示', kind: 'system', text: '中段：19字已聚，阿简托付于你。继续入深处，寻回余下碎甲。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-020',
      checkpoint: true,
    },
    {
      id: 'chapter-7-wrong-scroll-seek-020',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '补水之瓮的土层里沉着微光。挖出「粥」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-020',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-020',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识粥字', detail: '观察骨纹，认出这是「粥」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-021',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-021',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '归档木匣的土层里沉着微光。挖出「饼」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-021',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-021',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识饼字', detail: '观察骨纹，认出这是「饼」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-022',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-022',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '点校案头的土层里沉着微光。挖出「汤」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-022',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-022',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识汤字', detail: '观察骨纹，认出这是「汤」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-023',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-023',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '注疏残页的土层里沉着微光。挖出「字」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-023',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-023',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识字字', detail: '观察骨纹，认出这是「字」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-024',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-024',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '校对之尺的土层里沉着微光。挖出「麦」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-024',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-024',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识麦字', detail: '观察骨纹，认出这是「麦」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-025',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-025',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '勘误灯下的土层里沉着微光。挖出「蔬」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-025',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-025',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识蔬字', detail: '观察骨纹，认出这是「蔬」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-026',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-026',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '拾遗字堆的土层里沉着微光。挖出「家」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-026',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-026',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识家字', detail: '观察骨纹，认出这是「家」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-027',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-027',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '归架之格的土层里沉着微光。挖出「房」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-027',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-027',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识房字', detail: '观察骨纹，认出这是「房」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-028',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-028',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '誊录之笔的土层里沉着微光。挖出「屋」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-028',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-028',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识屋字', detail: '观察骨纹，认出这是「屋」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-029',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-029',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '封泥待钤的土层里沉着微光。挖出「门」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-029',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-029',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识门字', detail: '观察骨纹，认出这是「门」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-030',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-030',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '契痕犹在的土层里沉着微光。挖出「窗」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-030',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-030',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识窗字', detail: '观察骨纹，认出这是「窗」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-031',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-031',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '院中晾简的土层里沉着微光。挖出「墙」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-031',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-031',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识墙字', detail: '观察骨纹，认出这是「墙」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-032',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-032',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '檐下悬册的土层里沉着微光。挖出「桌」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-032',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-032',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识桌字', detail: '观察骨纹，认出这是「桌」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-033',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-033',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '将焚书堆的土层里沉着微光。挖出「椅」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-033',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-033',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识椅字', detail: '观察骨纹，认出这是「椅」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-034',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-034',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '余火边缘的土层里沉着微光。挖出「床」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-034',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-034',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识床字', detail: '观察骨纹，认出这是「床」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-035',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-035',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '错简交叠的土层里沉着微光。挖出「灯」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-035',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-035',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识灯字', detail: '观察骨纹，认出这是「灯」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-036',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-036',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '墨迹漫漶的土层里沉着微光。挖出「楼」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-036',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-036',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识楼字', detail: '观察骨纹，认出这是「楼」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-037',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-037',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '残卷夹层的土层里沉着微光。挖出「契」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-037',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-037',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识契字', detail: '观察骨纹，认出这是「契」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-seek-038',
    },
    {
      id: 'chapter-7-wrong-scroll-seek-038',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 寻骨', detail: '焦黄书页的土层里沉着微光。挖出「院」字碎片。', targetRadius: 105 },
      completeOn: 'excavation-completed',
      nextStepId: 'chapter-7-wrong-scroll-lesson-038',
    },
    {
      id: 'chapter-7-wrong-scroll-lesson-038',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 辨识院字', detail: '观察骨纹，认出这是「院」字碎片所记之物，正确辨认。' },
      completeOn: 'learning-completed',
      nextStepId: 'chapter-7-wrong-scroll-fragment-awakens',
    },
    {
      id: 'chapter-7-wrong-scroll-fragment-awakens',
      chapterId: CHAPTER_SEVEN_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '38枚文献辨伪碎甲在掌心排开。你按这一程的脉络理好，骨纹竟投出一道微光，照见阿简要办之事的去向。' },
        { speaker: '神秘低语', text: '……文献辨伪毕，骨已成章……' },
        { speaker: '你', text: '原来这一程记下的不是死物，是「掌血汗泪、气声音乐、米菜瓜果茶酒肉蛋油盐糖粥饼汤、字麦蔬家房屋门窗户墙桌椅床灯楼契院」里活着的学问。它们齐了，去路才显在眼前。' },
        { speaker: '守册·阿简', text: '我听不见金光里的声音，可骨片真的在你手里连成了路！守卜人，你果然是贞人师说的那个人。' },
        { speaker: '提示', kind: 'system', text: '获得：「掌血汗泪、气声音乐、米菜瓜果茶酒肉蛋油盐糖粥饼汤、字麦蔬家房屋门窗户墙桌椅床灯楼契院」38枚文献辨伪甲骨碎片。卜力已苏醒，可落为天意之辞。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-7-wrong-scroll-first-request',
    },
    {
      id: 'chapter-7-wrong-scroll-first-request',
      chapterId: CHAPTER_SEVEN_ID,
      dialogue: [
        { speaker: '旁白', kind: 'narration', text: '38枚碎甲归位，阿简这一桩「文献辨伪」的脉络已清。可尚有未解的悬疑，要借卜力一问。' },
        { speaker: '守册·阿简', text: '守卜人，这38枚甲骨记下的事，我已信了八九分。可还有三桩悬案，能用这些字卜一卜么？' },
        { speaker: '你', text: '（你斟酌：三问牵连，当一卜接一卜地解。取过一枚甲骨——先卜其一，其余的，且待兆纹引你去看。）' },
        { speaker: '贞人师', text: '去吧。以这一程的卜力，为阿简卜算「真伪之辨、抢救之序、归架之时」三桩悬案。每解一桩，卜力便积一分。' },
        { speaker: '提示', kind: 'system', text: '守卜任务开启（第一轮）：为守册·阿简卜算「真伪之辨」，留意兆纹里多出的那道裂纹。' },
      ],
      completeOn: 'dialogue-completed',
      nextStepId: 'chapter-7-wrong-scroll-enter-temple',
      checkpoint: true,
    },
    {
      id: 'chapter-7-wrong-scroll-enter-temple',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第七章：错册余火 · 问卜', detail: '随守册·阿简返回宗庙内殿，准备以本章甲骨问卜。', storyLocationId: 'city-divination-temple', targetRadius: 110 },
      completeOn: 'temple-entered',
      nextStepId: 'chapter-7-wrong-scroll-take-seat',
    },
    {
      id: 'chapter-7-wrong-scroll-take-seat',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '问卜 · 入席', detail: '走到内殿占卜席前，点击“坐下”，听守册·阿简讲清要卜之事。' },
      completeOn: 'temple-seat-reached',
      nextStepId: 'chapter-7-wrong-scroll-divination-1',
    },
    {
      id: 'chapter-7-wrong-scroll-divination-1',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第1轮问卜 · 真伪之辨', detail: '守册·阿简请你以本章甲骨卜算「真伪之辨」。' },
      completeOn: 'divination-completed',
      nextStepId: 'chapter-7-wrong-scroll-divination-2',
      checkpoint: true,
    },
    {
      id: 'chapter-7-wrong-scroll-divination-2',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第2轮问卜 · 抢救之序', detail: '守册·阿简请你以本章甲骨卜算「抢救之序」。' },
      completeOn: 'divination-completed',
      nextStepId: 'chapter-7-wrong-scroll-divination-3',
      checkpoint: true,
    },
    {
      id: 'chapter-7-wrong-scroll-divination-3',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '第3轮问卜 · 归架之时', detail: '守册·阿简请你以本章甲骨卜算「归架之时」。' },
      completeOn: 'divination-completed',
      nextStepId: 'chapter-7-wrong-scroll-leave-seat',
    },
    {
      id: 'chapter-7-wrong-scroll-leave-seat',
      chapterId: CHAPTER_SEVEN_ID,
      objective: { title: '异常兆纹', detail: '完成三轮占卜后起身，查看甲骨额外显出的那道裂纹。' },
      completeOn: 'result-confirmed',
      nextStepId: 'chapter-7-wrong-scroll-clue-revealed',
    },
    {
      id: 'chapter-7-wrong-scroll-clue-revealed',
      chapterId: CHAPTER_SEVEN_ID,
      dialogue: [
        { speaker: '守册·阿简', text: '原来「真伪之辨、抢救之序、归架之时」三问，兆纹都指向下一处——典册归架，裂纹却指向城外王陵——三证未齐，陵门不开。' },
        { speaker: '旁白', kind: 'narration', text: '三卜既毕，兆纹并未熄灭。几道裂纹缓缓延伸，竟越过这一程，指向「王陵三证」。' },
        { speaker: '神秘低语', text: '……王陵三证……有骨……待人相续……' },
        { speaker: '贞人师', text: '三轮卜辞彼此牵引，这道裂纹拐出了这一程——下一处碎甲，在「王陵三证」里。' },
        { speaker: '提示', kind: 'system', text: '第七章：错册余火完成。获得线索「王陵三证」，下一章已开启。' },
      ],
      completeOn: 'dialogue-completed',
      checkpoint: true,
    },
  ],
};
